UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119723;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119724;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119725;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119726;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119727;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119728;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119729;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119730;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119731;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119732;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119733;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119734;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119735;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119736;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119737;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119738;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119739;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119740;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119741;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119742;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119743;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119744;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119745;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119746;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119747;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119748;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119749;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119750;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119751;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119752;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119753;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119754;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119755;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119756;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119757;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119758;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119759;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119760;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119761;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119762;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119763;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119764;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119765;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119766;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119767;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119768;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119723, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119724, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119725, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119726, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119727, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119728, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119729, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119730, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119731, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119732, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119733, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119734, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119735, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119736, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119737, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119738, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119739, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119740, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119741, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119742, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119743, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119744, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119745, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119746, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119747, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119748, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119749, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119750, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119751, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119752, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119753, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119754, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119755, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119756, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119757, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119758, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119759, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119760, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119761, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119762, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119763, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119764, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119765, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119766, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119767, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119768, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119723, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119724, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119725, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119726, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119727, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119728, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119729, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119730, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119731, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119732, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119733, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119734, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119735, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119736, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119737, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119738, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119739, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119740, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119741, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119742, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119743, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119744, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119745, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119746, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119747, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119748, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119749, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119750, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119751, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119752, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119753, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119754, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119755, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119756, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119757, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119758, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119759, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119760, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119761, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119762, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119763, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119764, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119765, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119766, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119767, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119768, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
