UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119526;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119527;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119528;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119529;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119530;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119531;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119532;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119533;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119534;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119535;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119536;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119537;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119538;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119539;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119540;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119541;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119542;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119543;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119544;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119545;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119546;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119547;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119548;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119549;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119550;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119551;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119552;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119553;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119554;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119555;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119556;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119557;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119558;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119559;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119560;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119561;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119562;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119563;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119564;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119565;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119566;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119567;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119568;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119569;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119570;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119571;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119572;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119573;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119574;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119575;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119576;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119577;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119578;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119579;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119580;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119581;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119582;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119583;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119584;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119585;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119586;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119587;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119588;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119589;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119590;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119591;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119592;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119593;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119594;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119595;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119596;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119597;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119598;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119599;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119600;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119601;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119602;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119603;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119604;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119605;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119606;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119607;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119526, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119527, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119528, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119529, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119530, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119531, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119532, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119533, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119534, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119535, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119536, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119537, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119538, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119539, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119540, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119541, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119542, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119543, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119544, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119545, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119546, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119547, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119548, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119549, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119550, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119551, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119552, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119553, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119554, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119555, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119556, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119557, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119558, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119559, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119560, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119561, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119562, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119563, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119564, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119565, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119566, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119567, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119568, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119569, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119570, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119571, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119572, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119573, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119574, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119575, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119576, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119577, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119578, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119579, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119580, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119581, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119582, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119583, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119584, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119585, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119586, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119587, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119588, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119589, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119590, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119591, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119592, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119593, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119594, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119595, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119596, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119597, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119598, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119599, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119600, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119601, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119602, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119603, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119604, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119605, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119606, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119607, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119526, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119527, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119528, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119529, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119530, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119531, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119532, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119533, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119534, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119535, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119536, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119537, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119538, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119539, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119540, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119541, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119542, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119543, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119544, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119545, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119546, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119547, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119548, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119549, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119550, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119551, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119552, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119553, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119554, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119555, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119556, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119557, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119558, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119559, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119560, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119561, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119562, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119563, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119564, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119565, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119566, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119567, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119568, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119569, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119570, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119571, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119572, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119573, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119574, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119575, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119576, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119577, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119578, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119579, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119580, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119581, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119582, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119583, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119584, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119585, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119586, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119587, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119588, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119589, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119590, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119591, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119592, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119593, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119594, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119595, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119596, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119597, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119598, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119599, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119600, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119601, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119602, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119603, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119604, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119605, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119606, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119607, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
