UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 4208;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 5770;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 5771;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 5895;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6089;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6090;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6091;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6121;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6122;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6123;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6252;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6295;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6340;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6341;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 6563;
UPDATE gedung_bangunan SET id_sub_skpd = 403 WHERE id = 4383;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 4208;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 5770;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 5771;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 5895;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6089;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6090;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6091;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6121;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6122;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6123;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6252;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6295;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6340;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6341;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6563;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 4383;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (4208, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (5770, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (5771, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (5895, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6089, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6090, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6091, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6121, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6122, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6123, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6252, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6295, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6340, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6341, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6563, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (4383, 40) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 40;
