UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100072;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100073;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100081;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100096;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100097;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100099;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100101;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100102;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100103;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100104;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100105;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 100106;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1005;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1021;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 12470;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1471;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1475;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1555;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1564;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1586;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 31967;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 31969;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 33458;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 33459;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 3614;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 3630;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 3649;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 3967;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 40028;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4098;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 45020;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 45021;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 45026;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4549;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4575;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4931;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 50205;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 50206;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 50207;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 50208;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 608;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 640;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69111;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69112;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69114;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69115;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69116;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69117;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69118;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69119;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69120;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69121;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 69124;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 71083;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 727;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 8068;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 98322;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 98323;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 99716;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1064;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 12448;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 15244;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4148;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4181;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4193;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 808;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 8132;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 824;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1074;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 15264;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1565;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1606;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 1609;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 3939;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 3945;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 3948;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 42111;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 42113;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 45007;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 45015;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 45016;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4738;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4742;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4771;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4794;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4797;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4822;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4849;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4858;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4870;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 4878;
UPDATE peralatan_mesin SET id_sub_skpd = 56 WHERE id = 8114;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100072;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100073;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100081;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100096;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100097;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100099;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100101;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100102;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100103;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100104;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100105;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100106;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1005;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1021;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12470;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1471;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1475;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1555;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1564;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1586;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 31967;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 31969;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33458;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33459;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3614;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3630;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3649;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3967;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40028;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4098;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45020;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45021;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45026;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4549;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4575;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4931;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50205;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50206;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50207;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50208;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 608;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 640;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69111;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69112;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69114;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69115;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69116;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69117;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69118;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69119;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69120;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69121;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69124;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71083;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 727;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8068;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98322;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98323;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99716;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1064;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12448;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15244;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4148;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4181;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4193;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 808;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8132;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 824;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1074;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15264;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1565;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1606;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1609;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3939;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3945;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3948;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 42111;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 42113;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45007;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45015;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45016;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4738;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4742;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4771;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4794;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4797;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4822;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4849;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4858;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4870;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4878;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8114;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100072, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100073, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100081, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100096, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100097, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100099, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100101, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100102, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100103, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100104, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100105, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100106, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1005, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1021, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12470, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1471, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1475, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1555, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1564, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1586, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (31967, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (31969, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33458, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33459, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3614, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3630, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3649, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3967, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40028, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4098, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45020, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45021, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45026, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4549, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4575, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4931, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50205, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50206, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50207, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50208, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (608, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (640, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69111, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69112, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69114, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69115, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69116, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69117, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69118, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69119, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69120, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69121, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69124, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71083, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (727, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8068, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98322, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98323, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99716, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1064, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12448, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15244, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4148, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4181, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4193, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (808, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8132, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (824, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1074, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15264, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1565, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1606, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1609, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3939, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3945, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3948, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (42111, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (42113, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45007, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45015, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45016, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4738, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4742, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4771, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4794, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4797, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4822, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4849, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4858, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4870, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4878, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8114, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
