UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100379;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100381;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100382;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1011;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 101433;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 101435;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102115;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102116;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102117;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102118;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102147;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102318;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102319;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102320;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102321;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102322;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102336;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1041;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1052;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1100;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112033;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112034;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112035;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112036;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112037;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112038;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112039;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112040;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112050;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112051;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112052;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112053;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112054;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112698;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112699;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 140;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1506;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1513;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1514;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15541;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15544;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15549;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15554;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15555;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15557;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15561;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15562;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15564;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15565;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15566;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 210;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 2451;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 27;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 31968;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 32711;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 34577;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 34578;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 34589;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 350;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 386;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 39;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 39537;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 39540;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 39548;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 39550;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 40018;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 40019;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 40020;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 40021;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 40023;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 42272;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 435;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 438;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 44612;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 44614;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 44678;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 44696;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 44783;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 45040;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 45120;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 45121;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 49;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50063;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50065;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50067;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50075;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50076;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 56;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 59;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68643;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68644;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68647;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68648;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68649;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68650;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68652;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68653;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68654;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68713;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68714;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68715;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68716;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68718;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68719;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68720;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68721;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68723;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68772;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71754;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71758;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71760;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71765;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71766;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71824;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71915;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 71916;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 819;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 843;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 844;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 87329;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 87844;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88017;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88018;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88072;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88076;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88103;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88841;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88842;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88843;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88844;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88846;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88847;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88848;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88849;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88850;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 88856;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89176;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89180;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89181;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89183;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89185;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89186;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89187;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89190;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89191;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89192;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89193;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89224;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89225;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89226;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89227;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89231;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 89232;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97483;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97484;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97485;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97486;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97487;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97488;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97489;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97490;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97491;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97492;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97493;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97494;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97495;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97496;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97497;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97498;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97499;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97500;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97501;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 97502;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 99753;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 99994;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 15545;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 44615;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 45039;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50072;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50079;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 665;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 68651;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100086;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100088;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100089;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100090;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100091;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100092;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100093;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100094;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 100095;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 101434;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 101436;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102107;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102108;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102109;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102110;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102111;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102112;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102113;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102114;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 102337;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1071;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 110667;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 110668;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 111;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112042;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112043;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112048;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 112049;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1451;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 1485;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 290;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 293;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 294;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 308;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 309;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 356;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 357;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 358;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 359;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 360;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 405;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 50069;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 717;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 718;
UPDATE peralatan_mesin SET id_sub_skpd = 406 WHERE id = 99996;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100379;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100381;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100382;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1011;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101433;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101435;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102115;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102116;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102117;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102118;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102147;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102318;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102319;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102320;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102321;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102322;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102336;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1041;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1052;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1100;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112033;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112034;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112035;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112036;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112037;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112038;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112039;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112040;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112050;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112051;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112052;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112053;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112054;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112698;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112699;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 140;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1506;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1513;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1514;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15541;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15544;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15549;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15554;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15555;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15557;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15561;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15562;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15564;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15565;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15566;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 210;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2451;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 27;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 31968;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32711;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34577;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34578;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34589;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 350;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 386;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39537;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39540;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39548;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39550;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40018;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40019;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40020;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40021;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40023;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 42272;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 435;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 438;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44612;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44614;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44678;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44696;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44783;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45040;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45120;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45121;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50063;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50065;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50067;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50075;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50076;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 56;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68643;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68644;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68647;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68648;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68649;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68650;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68652;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68653;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68654;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68713;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68714;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68715;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68716;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68718;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68719;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68720;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68721;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68723;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68772;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71754;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71758;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71760;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71765;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71766;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71824;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71915;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71916;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 819;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 843;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 844;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87329;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87844;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88017;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88018;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88072;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88076;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88103;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88841;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88842;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88843;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88844;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88846;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88847;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88848;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88849;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88850;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88856;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89176;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89180;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89181;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89183;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89185;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89186;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89187;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89190;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89191;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89192;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89193;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89224;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89225;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89226;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89227;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89231;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89232;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97483;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97484;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97485;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97486;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97487;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97488;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97489;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97490;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97491;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97492;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97493;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97494;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97495;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97496;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97497;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97498;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97499;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97500;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97501;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97502;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99753;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99994;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15545;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44615;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45039;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50072;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50079;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 665;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68651;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100086;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100088;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100089;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100090;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100091;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100092;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100094;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100095;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101434;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101436;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102107;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102108;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102109;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102110;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102111;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102112;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102113;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102114;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102337;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1071;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 110667;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 110668;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 111;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112042;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112043;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112048;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112049;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1451;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1485;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 290;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 293;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 294;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 308;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 309;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 356;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 357;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 358;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 359;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 360;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 405;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50069;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 717;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 718;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99996;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100379, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100381, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100382, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1011, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101433, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101435, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102115, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102116, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102117, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102118, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102147, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102318, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102319, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102320, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102321, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102322, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102336, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1041, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1052, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1100, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112033, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112034, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112035, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112036, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112037, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112038, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112039, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112040, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112050, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112051, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112052, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112053, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112054, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112698, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112699, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (140, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1506, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1513, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1514, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15541, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15544, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15549, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15554, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15555, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15557, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15561, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15562, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15564, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15565, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15566, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (210, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2451, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (27, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (31968, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32711, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34577, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34578, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34589, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (350, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (386, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39537, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39540, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39548, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39550, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40018, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40019, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40020, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40021, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40023, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (42272, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (435, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (438, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44612, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44614, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44678, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44696, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44783, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45040, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45120, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45121, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50063, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50065, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50067, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50075, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50076, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (56, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68643, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68644, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68647, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68648, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68649, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68650, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68652, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68653, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68654, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68713, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68714, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68715, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68716, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68718, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68719, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68720, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68721, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68723, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68772, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71754, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71758, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71760, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71765, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71766, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71824, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71915, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71916, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (819, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (843, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (844, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87329, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87844, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88017, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88018, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88072, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88076, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88103, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88841, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88842, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88843, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88844, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88846, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88847, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88848, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88849, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88850, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88856, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89176, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89180, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89181, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89183, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89185, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89186, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89187, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89190, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89191, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89192, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89193, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89224, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89225, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89226, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89227, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89231, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89232, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97483, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97484, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97485, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97486, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97487, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97488, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97489, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97490, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97491, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97492, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97493, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97494, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97495, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97496, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97497, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97498, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97499, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97500, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97501, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97502, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99753, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99994, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15545, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44615, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45039, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50072, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50079, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (665, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68651, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100086, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100088, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100089, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100090, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100091, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100092, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100093, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100094, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100095, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101434, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101436, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102107, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102108, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102109, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102110, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102111, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102112, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102113, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102114, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102337, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1071, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (110667, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (110668, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (111, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112042, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112043, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112048, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112049, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1451, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1485, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (290, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (293, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (294, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (308, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (309, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (356, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (357, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (358, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (359, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (360, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (405, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50069, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (717, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (718, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99996, 47) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 47;
