UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118067;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118068;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118069;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118070;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118071;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118072;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118073;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118074;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118075;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118076;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118077;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118078;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118079;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118080;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118081;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118082;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118083;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118084;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118085;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118086;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118087;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118088;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118089;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118090;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118091;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118092;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118093;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118094;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118095;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118096;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118097;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118098;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118099;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118100;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118101;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118102;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118103;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118104;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118105;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118106;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118107;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118108;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118109;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118110;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118111;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118112;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118113;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118114;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118115;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118116;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118117;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118118;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118119;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118120;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118121;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118122;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118123;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118124;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118125;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118126;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118127;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118128;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118129;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118130;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118131;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118132;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118133;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118134;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118135;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118136;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118137;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118138;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118139;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118140;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118141;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118142;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118143;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118144;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118145;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118146;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118147;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118148;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118149;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118150;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118151;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118152;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118153;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118154;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118155;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118156;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118157;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118158;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118159;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118160;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118161;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118162;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118163;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118164;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118165;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118166;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118167;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118168;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118169;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118170;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118171;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118172;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118173;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118174;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118175;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118176;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118177;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118178;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118179;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118067, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118068, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118069, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118070, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118071, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118072, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118073, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118074, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118075, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118076, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118077, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118078, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118079, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118080, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118081, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118082, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118083, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118084, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118085, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118086, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118087, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118088, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118089, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118090, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118091, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118092, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118093, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118094, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118095, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118096, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118097, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118098, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118099, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118100, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118101, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118102, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118103, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118104, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118105, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118106, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118107, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118108, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118109, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118110, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118111, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118112, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118113, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118114, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118115, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118116, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118117, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118118, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118119, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118120, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118121, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118122, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118123, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118124, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118125, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118126, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118127, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118128, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118129, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118130, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118131, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118132, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118133, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118134, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118135, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118136, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118137, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118138, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118139, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118140, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118141, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118142, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118143, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118144, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118145, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118146, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118147, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118148, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118149, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118150, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118151, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118152, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118153, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118154, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118155, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118156, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118157, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118158, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118159, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118160, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118161, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118162, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118163, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118164, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118165, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118166, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118167, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118168, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118169, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118170, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118171, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118172, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118173, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118174, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118175, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118176, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118177, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118178, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118179, 22) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 22;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118067, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118068, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118069, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118070, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118071, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118072, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118073, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118074, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118075, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118076, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118077, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118078, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118079, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118080, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118081, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118082, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118083, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118084, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118085, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118086, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118087, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118088, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118089, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118090, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118091, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118092, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118093, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118094, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118095, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118096, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118097, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118098, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118099, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118100, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118101, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118102, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118103, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118104, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118105, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118106, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118107, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118108, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118109, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118110, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118111, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118112, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118113, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118114, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118115, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118116, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118117, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118118, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118119, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118120, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118121, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118122, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118123, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118124, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118125, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118126, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118127, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118128, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118129, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118130, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118131, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118132, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118133, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118134, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118135, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118136, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118137, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118138, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118139, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118140, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118141, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118142, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118143, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118144, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118145, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118146, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118147, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118148, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118149, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118150, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118151, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118152, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118153, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118154, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118155, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118156, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118157, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118158, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118159, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118160, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118161, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118162, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118163, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118164, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118165, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118166, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118167, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118168, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118169, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118170, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118171, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118172, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118173, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118174, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118175, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118176, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118177, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118178, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118179, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
