UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5470;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5471;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5472;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5473;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5474;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5475;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5476;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5477;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5478;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5479;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5480;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5481;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5482;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5483;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5484;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5485;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5486;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5487;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5488;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5489;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5490;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5491;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5492;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5493;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5494;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5495;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5496;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5497;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5498;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5499;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5500;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5501;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5502;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5503;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5504;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5505;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5506;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5507;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5508;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5509;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5510;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5511;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5512;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5513;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5514;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5515;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5516;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5517;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5518;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5519;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5520;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5521;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5522;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5523;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5524;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5525;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5526;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5527;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5528;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5529;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5530;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5531;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5532;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5533;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5534;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5535;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5536;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5537;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5538;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5539;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5540;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5541;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5542;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5543;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5544;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5545;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5546;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5547;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5548;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5549;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5550;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5551;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5552;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5553;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5554;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5555;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5556;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5557;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5558;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5559;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5560;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5561;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5562;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5563;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5564;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5565;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5566;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5567;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5568;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5569;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5570;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5571;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5572;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5573;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5574;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5575;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5576;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5577;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5470, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5471, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5472, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5473, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5474, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5475, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5476, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5477, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5478, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5479, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5480, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5481, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5482, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5483, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5484, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5485, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5486, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5487, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5488, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5489, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5490, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5491, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5492, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5493, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5494, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5495, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5496, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5497, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5498, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5499, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5500, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5501, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5502, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5503, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5504, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5505, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5506, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5507, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5508, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5509, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5510, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5511, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5512, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5513, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5514, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5515, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5516, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5517, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5518, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5519, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5520, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5521, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5522, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5523, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5524, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5525, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5526, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5527, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5528, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5529, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5530, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5531, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5532, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5533, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5534, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5535, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5536, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5537, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5538, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5539, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5540, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5541, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5542, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5543, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5544, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5545, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5546, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5547, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5548, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5549, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5550, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5551, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5552, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5553, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5554, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5555, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5556, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5557, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5558, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5559, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5560, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5561, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5562, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5563, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5564, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5565, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5566, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5567, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5568, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5569, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5570, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5571, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5572, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5573, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5574, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5575, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5576, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5577, 3) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 3;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5470, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5471, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5472, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5473, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5474, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5475, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5476, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5477, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5478, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5479, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5480, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5481, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5482, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5483, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5484, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5485, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5486, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5487, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5488, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5489, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5490, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5491, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5492, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5493, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5494, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5495, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5496, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5497, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5498, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5499, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5500, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5501, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5502, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5503, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5504, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5505, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5506, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5507, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5508, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5509, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5510, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5511, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5512, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5513, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5514, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5515, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5516, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5517, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5518, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5519, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5520, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5521, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5522, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5523, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5524, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5525, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5526, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5527, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5528, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5529, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5530, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5531, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5532, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5533, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5534, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5535, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5536, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5537, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5538, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5539, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5540, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5541, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5542, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5543, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5544, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5545, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5546, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5547, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5548, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5549, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5550, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5551, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5552, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5553, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5554, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5555, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5556, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5557, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5558, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5559, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5560, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5561, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5562, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5563, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5564, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5565, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5566, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5567, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5568, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5569, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5570, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5571, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5572, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5573, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5574, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5575, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5576, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5577, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
