UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 100889;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 100900;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 13098;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 2269;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 2306;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 2307;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 32100;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 32124;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 32125;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 39443;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 41751;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 44464;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 44465;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 44468;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 44491;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 44492;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 50127;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 50129;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68658;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68660;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68661;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68668;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68670;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68671;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68672;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68674;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68675;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68676;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68677;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68678;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68679;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68680;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68737;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68739;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68740;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68741;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68757;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68760;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68762;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68763;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68786;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 70788;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 70789;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 88488;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 88678;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 88679;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 89787;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 89788;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 89793;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 89797;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 89798;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 98692;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68602;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68603;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68604;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68605;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68606;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68607;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68608;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68609;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68610;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68611;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68612;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68613;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68614;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68615;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68616;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68617;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68618;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68619;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68620;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68621;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68707;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68708;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68709;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68726;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68727;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68728;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68729;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68730;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68731;
UPDATE peralatan_mesin SET id_sub_skpd = 17 WHERE id = 68732;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100889;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100900;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13098;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2269;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2306;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2307;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32100;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32124;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32125;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39443;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 41751;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44464;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44465;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44468;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44491;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44492;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50127;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50129;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68658;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68660;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68661;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68668;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68670;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68671;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68672;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68674;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68675;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68676;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68677;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68678;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68679;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68680;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68737;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68739;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68740;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68741;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68757;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68760;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68762;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68763;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68786;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70788;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70789;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88488;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88678;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88679;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89787;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89788;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89793;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89797;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89798;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98692;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68602;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68603;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68604;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68605;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68606;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68607;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68608;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68609;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68610;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68611;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68612;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68613;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68614;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68615;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68616;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68617;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68618;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68619;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68620;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68621;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68707;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68708;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68709;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68726;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68727;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68728;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68729;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68730;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68731;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68732;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100889, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100900, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13098, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2269, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2306, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2307, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32100, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32124, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32125, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39443, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (41751, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44464, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44465, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44468, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44491, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44492, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50127, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50129, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68658, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68660, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68661, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68668, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68670, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68671, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68672, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68674, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68675, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68676, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68677, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68678, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68679, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68680, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68737, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68739, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68740, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68741, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68757, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68760, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68762, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68763, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68786, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70788, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70789, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88488, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88678, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88679, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89787, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89788, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89793, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89797, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89798, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98692, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68602, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68603, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68604, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68605, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68606, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68607, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68608, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68609, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68610, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68611, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68612, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68613, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68614, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68615, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68616, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68617, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68618, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68619, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68620, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68621, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68707, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68708, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68709, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68726, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68727, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68728, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68729, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68730, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68731, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68732, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
