cp /var/www/html/php5_laporan/php5_projects/01_setwan/*.php   01_setwan
cp /var/www/html/php5_laporan/php5_projects/02_setda/*.php   02_setda
cp /var/www/html/php5_laporan/php5_projects/03_dpupr/*.php   03_dpupr
cp /var/www/html/php5_laporan/php5_projects/04_dishub/*.php   04_dishub
cp /var/www/html/php5_laporan/php5_projects/05_dinkes/*.php   05_dinkes
cp /var/www/html/php5_laporan/php5_projects/07_disdik/*.php   07_disdik
cp /var/www/html/php5_laporan/php5_projects/08_perpustakaan/*.php   08_perpustakaan
cp /var/www/html/php5_laporan/php5_projects/09_sosial/*.php   09_sosial
cp /var/www/html/php5_laporan/php5_projects/10_dpmd/*.php   10_dpmd
cp /var/www/html/php5_laporan/php5_projects/11_dpppa/*.php   11_dpppa
cp /var/www/html/php5_laporan/php5_projects/12_dukcatpil/*.php   12_dukcatpil
cp /var/www/html/php5_laporan/php5_projects/13_pertanian/*.php   13_pertanian
cp /var/www/html/php5_laporan/php5_projects/15_dkp/*.php   15_dkp
cp /var/www/html/php5_laporan/php5_projects/16_dkukmp/*.php   16_dkukmp
cp /var/www/html/php5_laporan/php5_projects/18_dpmptsp/*.php   18_dpmptsp
cp /var/www/html/php5_laporan/php5_projects/19_bkd/*.php   19_bkd
cp /var/www/html/php5_laporan/php5_projects/20_inspektorat/*.php   20_inspektorat
cp /var/www/html/php5_laporan/php5_projects/21_bappeda/*.php   21_bappeda
cp /var/www/html/php5_laporan/php5_projects/22_dlh/*.php   22_dlh
cp /var/www/html/php5_laporan/php5_projects/23_dko/*.php   23_dko
cp /var/www/html/php5_laporan/php5_projects/24_kesbangpol/*.php   24_kesbangpol
cp /var/www/html/php5_laporan/php5_projects/25_satpolpp/*.php   25_satpolpp
cp /var/www/html/php5_laporan/php5_projects/26_bkppd/*.php   26_bkppd
cp /var/www/html/php5_laporan/php5_projects/28_paringin/*.php   28_paringin
cp /var/www/html/php5_laporan/php5_projects/31_lampihong/*.php   31_lampihong
cp /var/www/html/php5_laporan/php5_projects/32_batumandi/*.php   32_batumandi
cp /var/www/html/php5_laporan/php5_projects/33_juai/*.php   33_juai
cp /var/www/html/php5_laporan/php5_projects/34_awayan/*.php   34_awayan
cp /var/www/html/php5_laporan/php5_projects/35_halong/*.php   35_halong
cp /var/www/html/php5_laporan/php5_projects/36_paringinselatan/*.php   36_paringinselatan
cp /var/www/html/php5_laporan/php5_projects/38_tebingtinggi/*.php   38_tebingtinggi
cp /var/www/html/php5_laporan/php5_projects/39_bpbd/*.php   39_bpbd
cp /var/www/html/php5_laporan/php5_projects/40_dpkp/*.php   40_dpkp
cp /var/www/html/php5_laporan/php5_projects/41_disnakertrans/*.php   41_disnakertrans
cp /var/www/html/php5_laporan/php5_projects/42_dppkb/*.php   42_dppkb
cp /var/www/html/php5_laporan/php5_projects/43_kominfo/*.php   43_kominfo
cp /var/www/html/php5_laporan/php5_projects/44_kearsipan/*.php   44_kearsipan
cp /var/www/html/php5_laporan/php5_projects/45_perikanan/*.php   45_perikanan
cp /var/www/html/php5_laporan/php5_projects/46_pariwisata/*.php   46_pariwisata
cp /var/www/html/php5_laporan/php5_projects/47_perdagangan/*.php   47_perdagangan
cp /var/www/html/php5_laporan/php5_projects/48_bppd/*.php   48_bppd
