UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100737;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100738;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100739;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100740;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100810;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100811;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100812;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100813;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100814;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100815;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100818;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 100819;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 101123;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 101124;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 112026;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 112703;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 12451;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 12456;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 12467;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 12469;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 12474;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1478;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1490;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1522;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 15254;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 15294;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 15296;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1537;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1538;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1542;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1543;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1544;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1546;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1557;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1559;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1561;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1562;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1563;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 26421;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34815;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34849;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34850;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34917;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34918;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34919;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34922;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34923;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34924;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34925;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34929;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34932;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34933;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34935;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 34940;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 35016;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 375;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 39366;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4084;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 40878;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4090;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4093;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 40991;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4128;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44249;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44257;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44263;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44269;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44270;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44272;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44276;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44278;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44281;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44286;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44288;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44289;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44291;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44293;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44294;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44295;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4466;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4503;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4592;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4632;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4649;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4669;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4679;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4680;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4684;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4695;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4720;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4728;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 49890;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 49891;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 49892;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 49893;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 49894;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 49895;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 50519;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 50520;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 50521;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 50785;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 50786;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52875;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52876;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52877;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52878;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52879;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52880;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52881;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52882;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52883;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52884;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52885;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59804;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59805;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59813;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59814;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59815;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59816;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59817;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59818;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59819;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59820;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59821;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59822;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59823;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59824;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59825;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59826;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59827;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 59828;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 70953;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 70954;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 70995;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 8521;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88061;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88481;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88482;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88484;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88485;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88486;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88487;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88513;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88514;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88515;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88528;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88530;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88531;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88702;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88703;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88704;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88705;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88706;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88708;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88713;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88714;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88715;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88716;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88717;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88779;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88780;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88790;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88791;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88792;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88793;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88794;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88795;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88796;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88797;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88798;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88802;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88804;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88806;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88807;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88808;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88809;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88810;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88811;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88812;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88813;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88814;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88815;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88816;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88817;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88818;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88922;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88923;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 88924;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 97854;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 97855;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 98112;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 98114;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 98115;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 12450;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1430;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 1577;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 3488;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44260;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 44287;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4687;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4692;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4694;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 4954;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 50787;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 50788;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52873;
UPDATE peralatan_mesin SET id_sub_skpd = 26 WHERE id = 52874;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100737;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100738;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100739;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100740;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100810;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100811;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100812;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100813;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100814;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100815;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100818;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100819;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101123;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101124;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112026;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112703;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12451;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12456;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12467;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12469;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12474;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1478;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1490;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1522;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15254;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15294;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15296;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1537;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1538;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1542;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1543;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1544;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1546;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1557;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1559;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1561;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1562;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1563;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 26421;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34815;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34849;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34850;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34917;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34918;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34919;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34922;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34923;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34924;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34925;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34929;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34932;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34933;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34935;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34940;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35016;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 375;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39366;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4084;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40878;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4090;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40991;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4128;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44249;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44257;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44263;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44269;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44270;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44272;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44276;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44278;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44281;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44286;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44288;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44289;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44291;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44293;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44294;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44295;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4466;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4503;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4592;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4632;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4649;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4669;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4679;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4680;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4684;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4695;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4720;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4728;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49890;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49891;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49892;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49893;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49894;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49895;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50519;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50520;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50521;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50785;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50786;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52875;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52876;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52877;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52878;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52879;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52880;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52881;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52882;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52883;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52884;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52885;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59804;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59805;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59813;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59814;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59815;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59816;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59817;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59818;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59819;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59820;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59821;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59822;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59823;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59824;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59825;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59826;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59827;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59828;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70953;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70954;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70995;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8521;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88061;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88481;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88482;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88484;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88485;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88486;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88487;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88513;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88514;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88515;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88528;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88530;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88531;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88702;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88703;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88704;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88705;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88706;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88708;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88713;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88714;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88715;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88716;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88717;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88779;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88780;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88790;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88791;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88792;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88793;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88794;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88795;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88796;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88797;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88798;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88802;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88804;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88806;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88807;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88808;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88809;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88810;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88811;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88812;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88813;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88814;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88815;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88816;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88817;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88818;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88922;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88923;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88924;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97854;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97855;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98112;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98114;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98115;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12450;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1430;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1577;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3488;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44260;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44287;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4687;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4692;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4694;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4954;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50787;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50788;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52873;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52874;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100737, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100738, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100739, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100740, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100810, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100811, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100812, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100813, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100814, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100815, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100818, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100819, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101123, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101124, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112026, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112703, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12451, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12456, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12467, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12469, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12474, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1478, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1490, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1522, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15254, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15294, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15296, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1537, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1538, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1542, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1543, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1544, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1546, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1557, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1559, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1561, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1562, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1563, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (26421, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34815, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34849, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34850, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34917, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34918, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34919, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34922, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34923, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34924, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34925, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34929, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34932, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34933, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34935, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34940, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35016, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (375, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39366, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4084, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40878, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4090, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4093, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40991, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4128, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44249, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44257, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44263, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44269, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44270, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44272, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44276, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44278, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44281, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44286, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44288, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44289, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44291, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44293, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44294, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44295, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4466, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4503, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4592, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4632, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4649, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4669, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4679, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4680, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4684, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4695, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4720, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4728, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49890, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49891, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49892, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49893, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49894, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49895, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50519, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50520, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50521, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50785, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50786, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52875, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52876, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52877, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52878, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52879, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52880, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52881, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52882, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52883, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52884, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52885, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59804, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59805, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59813, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59814, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59815, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59816, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59817, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59818, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59819, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59820, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59821, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59822, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59823, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59824, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59825, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59826, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59827, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59828, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70953, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70954, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70995, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8521, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88061, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88481, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88482, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88484, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88485, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88486, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88487, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88513, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88514, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88515, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88528, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88530, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88531, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88702, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88703, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88704, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88705, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88706, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88708, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88713, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88714, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88715, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88716, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88717, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88779, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88780, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88790, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88791, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88792, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88793, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88794, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88795, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88796, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88797, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88798, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88802, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88804, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88806, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88807, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88808, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88809, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88810, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88811, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88812, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88813, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88814, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88815, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88816, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88817, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88818, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88922, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88923, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88924, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97854, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97855, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98112, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98114, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98115, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12450, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1430, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1577, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3488, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44260, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44287, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4687, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4692, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4694, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4954, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50787, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50788, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52873, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52874, 42) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 42;
