UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100747;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100748;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100749;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100902;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 10598;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 11687;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 1825;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 23989;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 32015;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 32093;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 32095;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 34887;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 35890;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 37100;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44429;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44432;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44433;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44434;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44435;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44436;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44437;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44438;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44446;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44447;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44448;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44449;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44451;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44463;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44467;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44469;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44470;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44479;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44485;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44487;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44488;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44489;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44490;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44501;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 49996;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 50002;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 50136;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 50137;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 50142;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68622;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68623;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68624;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68625;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68626;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68627;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68628;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68629;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68631;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68632;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68633;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68634;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68681;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68692;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68694;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68695;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68696;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68697;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68698;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68699;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68702;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68703;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68704;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68705;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68706;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68712;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68734;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68735;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68736;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68745;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68746;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68748;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68750;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68751;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68752;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68753;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68754;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68755;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68761;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68764;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68778;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68785;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 70790;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88489;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88490;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88491;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88492;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88493;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88681;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88682;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88928;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88929;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88930;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88931;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 89795;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 89796;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 89854;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 89855;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 954;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 97476;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 97477;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 97478;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 97479;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 97480;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 97481;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 97482;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98294;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98684;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98685;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98686;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98690;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98691;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98699;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 10527;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 2576;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 39439;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 44450;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68630;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68662;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68663;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68742;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100890;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100891;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100892;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100893;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100894;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 100895;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 2988;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 37235;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 50147;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68710;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68711;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68724;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68725;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68743;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 68781;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88680;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88932;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 88933;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 89791;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 89792;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98687;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98688;
UPDATE peralatan_mesin SET id_sub_skpd = 432 WHERE id = 98689;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100747;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100748;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100749;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100902;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 10598;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 11687;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1825;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23989;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32015;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32095;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34887;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35890;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 37100;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44429;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44432;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44433;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44434;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44435;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44436;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44437;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44438;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44446;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44447;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44448;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44449;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44451;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44463;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44467;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44469;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44470;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44479;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44485;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44487;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44488;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44489;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44490;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44501;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49996;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50002;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50136;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50137;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50142;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68622;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68623;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68624;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68625;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68626;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68627;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68628;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68629;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68631;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68632;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68633;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68634;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68681;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68692;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68694;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68695;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68696;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68697;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68698;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68699;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68702;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68703;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68704;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68705;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68706;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68712;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68734;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68735;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68736;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68745;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68746;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68748;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68750;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68751;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68752;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68753;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68754;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68755;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68761;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68764;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68778;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68785;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70790;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88489;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88490;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88491;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88492;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88493;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88681;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88682;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88928;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88929;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88930;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88931;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89795;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89796;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89854;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89855;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 954;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97476;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97477;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97478;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97479;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97480;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97481;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97482;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98294;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98684;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98685;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98686;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98690;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98691;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98699;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 10527;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2576;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39439;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44450;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68630;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68662;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68663;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68742;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100890;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100891;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100892;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100893;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100894;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100895;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2988;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 37235;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50147;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68710;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68711;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68724;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68725;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68743;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68781;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88680;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88932;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88933;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89791;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89792;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98687;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98688;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98689;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100747, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100748, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100749, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100902, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (10598, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (11687, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1825, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23989, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32015, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32093, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32095, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34887, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35890, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (37100, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44429, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44432, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44433, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44434, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44435, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44436, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44437, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44438, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44446, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44447, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44448, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44449, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44451, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44463, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44467, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44469, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44470, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44479, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44485, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44487, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44488, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44489, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44490, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44501, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49996, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50002, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50136, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50137, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50142, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68622, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68623, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68624, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68625, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68626, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68627, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68628, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68629, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68631, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68632, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68633, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68634, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68681, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68692, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68694, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68695, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68696, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68697, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68698, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68699, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68702, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68703, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68704, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68705, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68706, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68712, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68734, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68735, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68736, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68745, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68746, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68748, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68750, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68751, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68752, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68753, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68754, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68755, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68761, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68764, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68778, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68785, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70790, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88489, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88490, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88491, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88492, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88493, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88681, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88682, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88928, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88929, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88930, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88931, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89795, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89796, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89854, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89855, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (954, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97476, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97477, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97478, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97479, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97480, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97481, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97482, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98294, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98684, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98685, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98686, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98690, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98691, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98699, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (10527, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2576, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39439, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44450, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68630, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68662, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68663, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68742, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100890, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100891, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100892, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100893, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100894, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100895, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2988, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (37235, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50147, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68710, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68711, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68724, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68725, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68743, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68781, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88680, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88932, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88933, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89791, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89792, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98687, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98688, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98689, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
