UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100012;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100014;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100064;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100065;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100069;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100098;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100118;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100119;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100121;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100122;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100123;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100124;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100126;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100127;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100128;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100129;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 100130;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 101073;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 101104;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 101439;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 101440;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 101441;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 112022;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 112023;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 112024;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 112025;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 112091;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 112556;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2712;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2756;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2790;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2801;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2834;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2839;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2868;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2877;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2879;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 28913;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 28914;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 28916;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 28937;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2894;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 29003;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 29025;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 29046;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2914;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2918;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2953;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2970;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3026;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3043;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3045;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3048;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3050;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3053;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3057;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3064;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3066;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3077;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3080;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3086;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3093;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32826;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32827;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32828;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32829;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32830;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32831;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32832;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32834;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32836;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32837;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 32838;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35059;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35062;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35097;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35098;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35099;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35101;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35166;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35167;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35182;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35183;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35184;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35192;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35327;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35330;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 35337;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3681;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3682;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3685;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3691;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3694;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3717;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3744;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3745;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3747;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3748;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3749;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3751;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3753;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3755;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3756;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3757;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3782;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3848;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3869;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3903;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39384;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39570;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39571;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39665;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39666;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39667;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39668;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39670;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39671;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39672;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39673;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39674;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39675;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39676;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39677;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39678;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39679;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39680;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39681;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39683;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39684;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39685;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39686;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39687;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39688;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39689;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39690;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39691;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39692;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39693;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 39694;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3973;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3986;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 3996;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4008;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 40174;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 40175;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 40176;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 40177;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4028;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4030;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4033;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4036;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4047;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4048;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4050;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4052;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4054;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4057;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4060;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4062;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4065;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 4076;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 40986;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 40987;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 41025;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 41026;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 44177;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 44178;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 49821;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 49879;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 50161;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 50167;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52177;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52179;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52181;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52185;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52322;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52329;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52365;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52370;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52375;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52376;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52436;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52478;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52822;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52823;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52824;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52841;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 52842;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59848;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59849;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59850;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59851;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59852;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59853;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59854;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59855;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59856;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59857;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59860;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59861;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59862;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 59863;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7374;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7383;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7391;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7403;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7420;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7421;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7423;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7483;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7491;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7498;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7503;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7510;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7515;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7522;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7523;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7573;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7574;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7575;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 7576;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 87449;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 87450;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 87451;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 87452;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 87910;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 87912;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 87913;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88421;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88426;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88435;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88438;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88787;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88788;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88819;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 88822;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89084;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89278;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89279;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89285;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89287;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89294;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89994;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89995;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89997;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89998;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 89999;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90000;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90001;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90007;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90471;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90598;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90599;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90601;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90602;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90665;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 90668;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95396;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95397;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95398;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95399;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95400;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95401;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95402;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95403;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95404;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 95405;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 97453;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 97459;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 99765;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 99997;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 99999;
UPDATE peralatan_mesin SET id_sub_skpd = 71 WHERE id = 2709;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100012;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100014;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100064;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100065;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100069;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100098;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100118;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100119;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100121;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100122;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100123;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100124;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100126;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100127;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100128;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100129;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100130;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101073;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101104;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101439;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101440;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 101441;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112022;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112023;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112024;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112025;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112091;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112556;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2712;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2756;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2790;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2801;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2834;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2839;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2868;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2877;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2879;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28913;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28914;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28916;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28937;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2894;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 29003;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 29025;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 29046;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2914;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2918;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2953;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2970;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3026;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3043;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3045;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3048;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3050;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3053;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3057;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3064;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3066;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3077;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3080;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3086;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32826;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32827;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32828;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32829;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32830;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32831;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32832;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32834;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32836;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32837;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32838;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35059;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35062;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35097;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35098;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35099;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35101;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35166;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35167;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35182;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35183;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35184;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35192;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35327;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35330;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35337;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3681;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3682;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3685;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3691;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3694;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3717;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3744;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3745;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3747;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3748;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3749;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3751;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3753;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3755;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3756;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3757;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3782;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3848;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3869;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3903;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39384;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39570;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39571;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39665;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39666;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39667;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39668;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39670;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39671;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39672;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39673;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39674;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39675;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39676;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39677;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39678;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39679;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39680;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39681;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39683;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39684;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39685;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39686;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39687;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39688;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39689;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39690;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39691;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39692;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39693;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39694;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3973;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3986;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3996;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4008;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40174;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40175;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40176;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40177;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4028;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4030;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4033;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4036;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4047;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4048;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4050;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4052;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4054;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4057;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4060;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4062;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4065;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4076;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40986;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40987;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 41025;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 41026;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44177;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44178;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49821;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49879;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50161;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50167;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52177;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52179;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52181;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52185;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52322;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52329;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52365;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52370;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52375;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52376;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52436;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52478;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52822;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52823;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52824;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52841;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52842;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59848;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59849;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59850;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59851;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59852;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59853;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59854;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59855;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59856;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59857;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59860;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59861;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59862;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59863;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7374;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7383;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7391;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7403;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7420;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7421;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7423;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7483;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7491;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7498;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7503;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7510;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7515;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7522;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7523;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7573;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7574;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7575;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 7576;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87449;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87450;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87451;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87452;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87910;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87912;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87913;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88421;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88426;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88435;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88438;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88787;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88788;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88819;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88822;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89084;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89278;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89279;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89285;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89287;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89294;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89994;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89995;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89997;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89998;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89999;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90000;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90001;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90007;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90471;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90598;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90599;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90601;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90602;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90665;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90668;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95396;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95397;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95398;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95399;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95400;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95401;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95402;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95403;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95404;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 95405;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97453;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97459;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99765;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99997;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99999;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2709;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100012, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100014, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100064, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100065, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100069, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100098, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100118, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100119, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100121, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100122, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100123, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100124, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100126, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100127, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100128, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100129, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100130, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101073, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101104, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101439, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101440, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (101441, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112022, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112023, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112024, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112025, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112091, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112556, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2712, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2756, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2790, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2801, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2834, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2839, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2868, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2877, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2879, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28913, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28914, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28916, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28937, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2894, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (29003, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (29025, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (29046, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2914, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2918, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2953, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2970, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3026, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3043, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3045, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3048, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3050, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3053, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3057, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3064, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3066, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3077, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3080, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3086, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3093, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32826, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32827, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32828, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32829, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32830, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32831, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32832, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32834, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32836, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32837, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32838, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35059, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35062, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35097, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35098, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35099, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35101, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35166, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35167, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35182, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35183, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35184, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35192, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35327, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35330, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35337, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3681, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3682, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3685, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3691, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3694, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3717, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3744, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3745, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3747, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3748, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3749, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3751, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3753, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3755, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3756, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3757, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3782, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3848, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3869, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3903, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39384, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39570, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39571, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39665, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39666, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39667, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39668, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39670, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39671, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39672, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39673, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39674, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39675, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39676, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39677, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39678, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39679, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39680, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39681, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39683, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39684, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39685, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39686, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39687, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39688, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39689, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39690, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39691, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39692, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39693, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39694, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3973, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3986, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3996, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4008, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40174, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40175, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40176, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40177, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4028, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4030, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4033, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4036, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4047, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4048, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4050, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4052, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4054, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4057, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4060, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4062, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4065, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4076, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40986, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40987, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (41025, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (41026, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44177, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44178, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49821, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49879, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50161, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50167, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52177, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52179, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52181, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52185, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52322, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52329, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52365, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52370, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52375, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52376, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52436, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52478, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52822, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52823, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52824, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52841, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52842, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59848, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59849, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59850, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59851, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59852, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59853, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59854, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59855, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59856, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59857, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59860, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59861, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59862, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59863, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7374, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7383, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7391, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7403, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7420, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7421, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7423, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7483, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7491, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7498, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7503, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7510, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7515, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7522, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7523, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7573, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7574, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7575, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (7576, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87449, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87450, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87451, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87452, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87910, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87912, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87913, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88421, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88426, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88435, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88438, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88787, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88788, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88819, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88822, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89084, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89278, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89279, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89285, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89287, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89294, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89994, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89995, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89997, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89998, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89999, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90000, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90001, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90007, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90471, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90598, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90599, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90601, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90602, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90665, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90668, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95396, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95397, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95398, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95399, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95400, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95401, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95402, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95403, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95404, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (95405, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97453, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97459, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99765, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99997, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99999, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2709, 15) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 15;
