UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 10290;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 10362;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 10367;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 10744;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 11006;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 11041;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 11054;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 111993;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 111994;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 11277;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 12522;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 12524;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 12530;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 12531;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 12959;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 12960;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 12964;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13090;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13093;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 131;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13117;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13228;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13287;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13296;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13301;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13341;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13348;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13424;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13427;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13429;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13430;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13431;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13432;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13433;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13440;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13441;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 13442;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 160;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 178;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 2184;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 22015;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 22176;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 23069;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 23284;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 23289;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 23291;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 23293;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 23463;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24505;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24549;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24550;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24551;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24552;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24553;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24554;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24555;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24556;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24557;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24558;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 24559;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 25709;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 25710;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 25711;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 25714;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 313;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 317;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32000;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32001;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32002;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32003;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32005;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32006;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32007;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32011;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32021;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32024;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 32986;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 332;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 33742;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34926;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34927;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34928;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34934;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34963;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34964;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34978;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34983;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 34997;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 35000;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 35012;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 3538;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 39440;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 39488;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 39489;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 40044;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 40045;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 40046;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 40223;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 40256;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 40257;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 40258;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 41748;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44411;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44416;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44431;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44456;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44471;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44472;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44494;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44495;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44496;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44497;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44499;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44505;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44573;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44579;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44581;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44591;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44603;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44605;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44606;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44607;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44608;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44609;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 44613;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4597;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4686;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4690;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4701;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4801;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4805;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 49802;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 49818;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 49819;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 49820;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4983;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 4987;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5149;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5162;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5165;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5246;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5249;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5251;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5278;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52808;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52809;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52810;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52811;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52812;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52813;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52814;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52815;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52821;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5285;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5288;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52886;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 5290;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 52924;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 59836;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 59837;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 61714;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 61715;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 61717;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 61718;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 6304;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 6307;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 6433;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 6545;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 6573;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 70997;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 70998;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 70999;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71001;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71002;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71003;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71004;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71005;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71006;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71077;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71078;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71079;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71080;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71084;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71085;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71086;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71087;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71088;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71089;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71090;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71091;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71092;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71093;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71553;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71568;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71569;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71583;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71584;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71661;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 71662;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 756;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 8753;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88003;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88004;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88005;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88006;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88007;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88009;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88010;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88011;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88425;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88429;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88432;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88433;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88436;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88437;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88441;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88624;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88625;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88626;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88627;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 88628;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97531;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97532;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97535;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97609;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97610;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97612;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97613;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97632;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97633;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97636;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97637;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97638;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97639;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97640;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 9780;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97846;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97847;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97848;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97849;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97850;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97851;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97852;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 97853;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 9786;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 98449;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 98450;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 98451;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 98452;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 99767;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 99772;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 99776;
UPDATE peralatan_mesin SET id_sub_skpd = 48 WHERE id = 99791;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 10290;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 10362;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 10367;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 10744;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 11006;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 11041;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 11054;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 111993;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 111994;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 11277;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12522;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12524;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12530;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12531;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12959;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12960;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12964;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13090;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 131;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13117;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13228;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13287;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13296;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13301;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13341;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13348;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13424;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13427;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13429;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13430;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13431;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13432;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13433;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13440;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13441;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13442;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 160;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 178;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2184;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 22015;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 22176;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23069;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23284;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23289;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23291;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23293;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23463;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24505;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24549;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24550;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24551;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24552;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24553;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24554;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24555;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24556;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24557;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24558;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24559;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 25709;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 25710;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 25711;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 25714;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 313;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 317;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32000;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32001;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32002;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32003;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32005;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32006;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32007;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32011;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32021;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32024;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 32986;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 332;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33742;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34926;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34927;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34928;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34934;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34963;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34964;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34978;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34983;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34997;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35000;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 35012;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3538;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39440;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39488;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39489;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40044;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40045;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40046;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40223;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40256;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40257;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40258;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 41748;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44411;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44416;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44431;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44456;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44471;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44472;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44494;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44495;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44496;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44497;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44499;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44505;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44573;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44579;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44581;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44591;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44603;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44605;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44606;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44607;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44608;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44609;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44613;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4597;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4686;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4690;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4701;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4801;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4805;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49802;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49818;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49819;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 49820;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4983;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4987;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5149;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5162;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5165;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5246;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5249;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5251;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5278;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52808;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52809;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52810;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52811;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52812;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52813;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52814;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52815;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52821;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5285;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5288;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52886;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5290;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52924;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59836;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59837;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 61714;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 61715;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 61717;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 61718;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 6304;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 6307;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 6433;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 6545;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 6573;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70997;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70998;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 70999;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71001;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71002;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71003;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71004;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71005;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71006;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71077;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71078;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71079;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71080;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71084;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71085;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71086;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71087;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71088;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71089;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71090;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71091;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71092;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71553;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71568;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71569;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71583;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71584;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71661;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71662;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 756;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8753;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88003;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88004;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88005;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88006;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88007;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88009;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88010;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88011;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88425;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88429;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88432;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88433;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88436;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88437;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88441;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88624;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88625;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88626;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88627;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88628;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97531;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97532;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97535;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97609;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97610;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97612;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97613;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97632;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97633;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97636;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97637;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97638;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97639;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97640;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 9780;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97846;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97847;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97848;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97849;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97850;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97851;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97852;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97853;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 9786;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98449;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98450;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98451;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98452;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99767;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99772;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99776;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99791;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (10290, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (10362, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (10367, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (10744, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (11006, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (11041, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (11054, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (111993, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (111994, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (11277, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12522, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12524, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12530, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12531, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12959, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12960, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12964, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13090, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13093, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (131, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13117, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13228, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13287, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13296, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13301, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13341, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13348, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13424, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13427, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13429, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13430, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13431, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13432, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13433, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13440, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13441, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13442, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (160, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (178, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2184, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (22015, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (22176, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23069, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23284, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23289, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23291, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23293, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23463, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24505, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24549, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24550, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24551, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24552, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24553, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24554, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24555, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24556, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24557, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24558, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24559, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (25709, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (25710, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (25711, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (25714, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (313, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (317, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32000, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32001, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32002, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32003, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32005, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32006, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32007, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32011, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32021, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32024, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (32986, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (332, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33742, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34926, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34927, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34928, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34934, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34963, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34964, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34978, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34983, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34997, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35000, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (35012, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3538, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39440, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39488, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39489, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40044, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40045, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40046, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40223, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40256, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40257, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40258, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (41748, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44411, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44416, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44431, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44456, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44471, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44472, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44494, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44495, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44496, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44497, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44499, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44505, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44573, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44579, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44581, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44591, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44603, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44605, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44606, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44607, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44608, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44609, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44613, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4597, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4686, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4690, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4701, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4801, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4805, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49802, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49818, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49819, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (49820, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4983, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4987, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5149, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5162, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5165, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5246, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5249, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5251, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5278, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52808, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52809, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52810, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52811, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52812, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52813, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52814, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52815, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52821, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5285, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5288, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52886, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5290, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52924, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59836, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59837, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (61714, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (61715, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (61717, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (61718, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (6304, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (6307, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (6433, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (6545, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (6573, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70997, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70998, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (70999, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71001, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71002, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71003, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71004, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71005, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71006, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71077, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71078, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71079, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71080, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71084, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71085, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71086, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71087, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71088, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71089, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71090, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71091, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71092, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71093, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71553, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71568, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71569, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71583, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71584, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71661, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71662, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (756, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8753, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88003, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88004, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88005, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88006, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88007, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88009, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88010, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88011, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88425, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88429, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88432, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88433, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88436, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88437, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88441, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88624, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88625, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88626, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88627, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88628, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97531, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97532, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97535, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97609, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97610, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97612, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97613, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97632, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97633, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97636, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97637, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97638, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97639, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97640, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (9780, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97846, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97847, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97848, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97849, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97850, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97851, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97852, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97853, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (9786, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98449, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98450, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98451, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98452, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99767, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99772, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99776, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99791, 44) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 44;
