UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119631;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119632;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119633;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119634;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119635;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119636;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119637;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119638;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119639;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119640;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119641;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119642;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119643;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119644;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119645;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119646;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119647;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119648;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119649;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119650;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119651;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119652;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119653;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119654;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119655;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119656;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119657;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119658;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119659;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119660;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119661;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119662;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119663;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119664;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119665;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119666;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119667;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119668;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119669;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119670;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119671;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119672;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119673;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119674;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119675;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119676;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119677;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119678;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119679;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119680;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119681;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119682;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119683;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119684;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119685;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119686;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119687;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119688;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119689;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119690;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119691;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119692;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119693;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119694;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119695;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119696;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119697;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119698;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119699;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119700;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119701;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119702;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119703;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119704;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119705;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119706;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119707;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119708;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119709;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119710;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119711;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119712;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119713;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119714;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119715;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119716;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119717;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119718;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119719;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119720;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119721;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119722;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119631, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119632, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119633, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119634, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119635, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119636, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119637, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119638, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119639, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119640, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119641, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119642, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119643, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119644, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119645, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119646, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119647, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119648, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119649, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119650, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119651, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119652, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119653, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119654, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119655, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119656, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119657, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119658, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119659, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119660, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119661, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119662, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119663, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119664, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119665, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119666, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119667, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119668, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119669, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119670, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119671, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119672, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119673, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119674, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119675, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119676, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119677, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119678, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119679, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119680, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119681, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119682, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119683, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119684, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119685, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119686, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119687, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119688, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119689, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119690, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119691, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119692, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119693, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119694, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119695, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119696, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119697, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119698, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119699, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119700, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119701, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119702, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119703, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119704, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119705, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119706, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119707, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119708, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119709, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119710, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119711, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119712, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119713, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119714, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119715, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119716, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119717, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119718, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119719, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119720, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119721, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119722, 9) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 9;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119631, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119632, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119633, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119634, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119635, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119636, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119637, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119638, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119639, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119640, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119641, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119642, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119643, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119644, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119645, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119646, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119647, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119648, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119649, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119650, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119651, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119652, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119653, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119654, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119655, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119656, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119657, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119658, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119659, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119660, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119661, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119662, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119663, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119664, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119665, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119666, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119667, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119668, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119669, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119670, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119671, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119672, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119673, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119674, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119675, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119676, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119677, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119678, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119679, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119680, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119681, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119682, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119683, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119684, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119685, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119686, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119687, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119688, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119689, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119690, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119691, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119692, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119693, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119694, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119695, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119696, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119697, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119698, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119699, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119700, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119701, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119702, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119703, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119704, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119705, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119706, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119707, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119708, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119709, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119710, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119711, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119712, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119713, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119714, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119715, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119716, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119717, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119718, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119719, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119720, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119721, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119722, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
