cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > peralatan_mesin_108_setda.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > peralatan_mesin_108_dpupr.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > peralatan_mesin_108_dishub.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > peralatan_mesin_108_dinkes.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"id_skpd = 1"/"id_skpd = 6"/g > peralatan_mesin_108_rsud.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > peralatan_mesin_108_disdik.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > peralatan_mesin_108_perpustakaan.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > peralatan_mesin_108_sosial.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > peralatan_mesin_108_dpmd.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > peralatan_mesin_108_dpppa.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > peralatan_mesin_108_dukcatpil.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > peralatan_mesin_108_pertanian.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 14"/g > peralatan_mesin_108_kehutanan.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > peralatan_mesin_108_dkp.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > peralatan_mesin_108_dkukmp.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"id_skpd = 1"/"id_skpd = 17"/g > peralatan_mesin_108_distamben.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > peralatan_mesin_108_dpmptsp.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > peralatan_mesin_108_bkd.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > peralatan_mesin_108_inspektorat.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > peralatan_mesin_108_bappeda.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > peralatan_mesin_108_dlh.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > peralatan_mesin_108_dko.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > peralatan_mesin_108_kesbangpol.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > peralatan_mesin_108_satpolpp.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > peralatan_mesin_108_bkppd.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"id_skpd = 1"/"id_skpd = 27"/g > peralatan_mesin_108_korpri.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > peralatan_mesin_108_paringin.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"id_skpd = 1"/"id_skpd = 29"/g > peralatan_mesin_108_paringinkota.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"id_skpd = 1"/"id_skpd = 30"/g > peralatan_mesin_108_paringintimur.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > peralatan_mesin_108_lampihong.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > peralatan_mesin_108_batumandi.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > peralatan_mesin_108_juai.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > peralatan_mesin_108_awayan.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > peralatan_mesin_108_halong.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > peralatan_mesin_108_paringinselatan.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"id_skpd = 1"/"id_skpd = 37"/g > peralatan_mesin_108_batupiring.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > peralatan_mesin_108_tebingtinggi.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > peralatan_mesin_108_bpbd.sql

cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > peralatan_mesin_108_dpkp.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > peralatan_mesin_108_disnakertrans.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > peralatan_mesin_108_dppkb.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > peralatan_mesin_108_kominfo.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > peralatan_mesin_108_kearsipan.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > peralatan_mesin_108_perikanan.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > peralatan_mesin_108_pariwisata.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > peralatan_mesin_108_perdagangan.sql
cat peralatan_mesin_108_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > peralatan_mesin_108_bppd.sql

cat peralatan_mesin_108_*.sql > ../gabungan_peralatan_mesin_108.sql
