UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117843;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117844;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117845;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117846;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117847;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117848;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117849;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117850;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117851;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117852;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117853;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117854;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117855;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117856;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117857;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117858;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117859;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117860;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117861;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117862;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117863;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117864;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117865;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117866;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117867;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117868;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117869;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117870;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117871;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117872;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117873;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117874;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117875;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117876;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117877;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117878;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117879;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117880;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117881;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117882;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117883;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117884;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117885;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117886;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117887;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117888;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117889;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117890;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117891;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117892;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117893;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117894;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117895;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117896;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117897;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117898;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117899;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117900;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117901;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117902;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117903;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117904;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117905;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117906;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117907;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117908;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117909;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117910;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117911;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117912;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117913;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117914;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117915;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117916;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117917;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117918;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117919;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117920;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117921;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117922;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117923;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117924;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117925;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117926;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117927;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117928;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117929;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117930;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117931;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117932;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117933;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117934;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117935;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117936;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117937;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117938;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117939;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117940;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117941;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117942;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117943;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117944;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117945;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117946;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117947;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117948;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117949;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117950;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117951;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117952;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117953;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117954;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117955;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117956;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117957;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117958;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117959;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117960;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117961;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117962;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117963;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117964;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117965;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117966;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117967;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117968;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117969;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117970;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117971;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117972;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117973;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117974;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117975;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117976;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117977;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117978;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117979;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117980;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117981;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117982;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117983;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117984;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117985;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117986;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117987;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117988;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117989;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117990;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117991;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117992;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117993;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117994;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117995;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117996;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117997;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117998;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117999;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118000;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118001;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118002;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118003;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118004;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118005;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118006;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118007;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118008;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118009;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118010;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118011;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118012;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118013;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118014;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118015;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118016;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118017;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118018;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118019;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118020;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118021;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118022;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118023;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118024;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118025;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118026;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118027;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118028;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118029;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118030;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118031;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118032;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118033;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118034;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118035;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118036;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118037;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118038;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118039;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118040;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118041;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118042;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118043;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118044;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118045;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118046;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118047;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118048;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118049;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118050;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118051;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118052;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118053;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118054;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118055;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118056;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118057;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118058;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118059;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118060;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118061;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118062;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118063;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118064;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118065;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118066;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117843, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117844, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117845, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117846, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117847, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117848, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117849, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117850, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117851, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117852, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117853, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117854, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117855, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117856, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117857, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117858, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117859, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117860, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117861, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117862, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117863, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117864, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117865, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117866, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117867, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117868, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117869, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117870, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117871, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117872, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117873, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117874, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117875, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117876, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117877, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117878, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117879, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117880, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117881, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117882, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117883, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117884, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117885, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117886, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117887, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117888, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117889, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117890, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117891, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117892, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117893, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117894, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117895, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117896, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117897, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117898, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117899, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117900, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117901, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117902, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117903, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117904, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117905, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117906, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117907, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117908, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117909, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117910, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117911, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117912, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117913, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117914, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117915, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117916, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117917, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117918, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117919, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117920, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117921, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117922, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117923, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117924, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117925, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117926, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117927, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117928, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117929, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117930, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117931, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117932, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117933, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117934, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117935, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117936, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117937, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117938, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117939, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117940, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117941, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117942, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117943, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117944, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117945, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117946, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117947, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117948, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117949, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117950, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117951, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117952, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117953, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117954, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117955, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117956, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117957, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117958, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117959, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117960, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117961, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117962, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117963, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117964, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117965, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117966, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117967, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117968, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117969, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117970, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117971, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117972, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117973, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117974, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117975, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117976, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117977, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117978, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117979, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117980, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117981, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117982, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117983, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117984, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117985, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117986, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117987, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117988, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117989, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117990, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117991, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117992, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117993, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117994, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117995, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117996, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117997, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117998, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117999, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118000, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118001, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118002, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118003, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118004, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118005, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118006, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118007, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118008, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118009, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118010, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118011, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118012, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118013, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118014, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118015, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118016, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118017, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118018, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118019, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118020, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118021, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118022, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118023, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118024, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118025, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118026, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118027, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118028, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118029, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118030, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118031, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118032, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118033, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118034, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118035, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118036, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118037, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118038, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118039, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118040, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118041, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118042, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118043, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118044, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118045, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118046, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118047, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118048, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118049, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118050, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118051, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118052, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118053, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118054, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118055, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118056, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118057, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118058, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118059, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118060, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118061, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118062, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118063, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118064, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118065, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118066, 3) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 3;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117843, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117844, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117845, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117846, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117847, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117848, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117849, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117850, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117851, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117852, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117853, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117854, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117855, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117856, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117857, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117858, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117859, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117860, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117861, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117862, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117863, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117864, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117865, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117866, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117867, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117868, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117869, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117870, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117871, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117872, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117873, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117874, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117875, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117876, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117877, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117878, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117879, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117880, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117881, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117882, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117883, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117884, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117885, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117886, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117887, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117888, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117889, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117890, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117891, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117892, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117893, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117894, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117895, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117896, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117897, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117898, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117899, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117900, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117901, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117902, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117903, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117904, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117905, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117906, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117907, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117908, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117909, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117910, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117911, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117912, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117913, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117914, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117915, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117916, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117917, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117918, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117919, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117920, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117921, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117922, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117923, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117924, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117925, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117926, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117927, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117928, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117929, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117930, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117931, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117932, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117933, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117934, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117935, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117936, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117937, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117938, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117939, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117940, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117941, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117942, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117943, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117944, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117945, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117946, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117947, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117948, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117949, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117950, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117951, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117952, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117953, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117954, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117955, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117956, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117957, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117958, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117959, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117960, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117961, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117962, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117963, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117964, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117965, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117966, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117967, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117968, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117969, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117970, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117971, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117972, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117973, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117974, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117975, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117976, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117977, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117978, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117979, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117980, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117981, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117982, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117983, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117984, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117985, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117986, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117987, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117988, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117989, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117990, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117991, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117992, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117993, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117994, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117995, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117996, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117997, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117998, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117999, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118000, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118001, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118002, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118003, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118004, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118005, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118006, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118007, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118008, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118009, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118010, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118011, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118012, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118013, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118014, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118015, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118016, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118017, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118018, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118019, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118020, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118021, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118022, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118023, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118024, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118025, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118026, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118027, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118028, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118029, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118030, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118031, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118032, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118033, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118034, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118035, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118036, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118037, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118038, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118039, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118040, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118041, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118042, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118043, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118044, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118045, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118046, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118047, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118048, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118049, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118050, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118051, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118052, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118053, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118054, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118055, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118056, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118057, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118058, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118059, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118060, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118061, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118062, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118063, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118064, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118065, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118066, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
