UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3765;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3773;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3776;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3777;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3779;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3780;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3783;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3785;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3786;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3787;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3788;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3789;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3790;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3791;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3792;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3793;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3795;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3796;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3797;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3798;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3800;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3806;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3807;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3809;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3812;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 3848;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4290;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4292;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4309;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4310;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4311;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4312;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4313;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4358;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4359;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4360;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4361;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4362;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4579;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4580;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4583;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4585;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4654;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4655;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4656;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4659;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4660;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4661;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4665;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4667;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4668;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4669;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4670;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4671;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4672;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4673;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4674;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4675;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4676;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4677;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4679;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4680;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4681;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4683;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4684;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4685;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4686;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4687;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4688;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4689;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4690;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4691;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4692;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4693;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4694;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4695;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4696;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4697;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4698;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4699;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4700;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4701;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4702;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4703;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4704;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4705;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4707;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4708;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4709;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4710;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4711;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4720;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4724;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4734;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4865;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4866;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4867;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4868;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4869;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4870;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4871;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4872;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4873;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4874;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4875;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4876;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 4987;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 617 WHERE id = 5137;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3765;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3773;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3776;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3777;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3779;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3780;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3783;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3785;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3786;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3787;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3788;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3789;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3790;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3791;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3792;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3793;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3795;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3796;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3797;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3798;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3800;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3806;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3807;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3809;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3812;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3848;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4290;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4292;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4309;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4310;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4311;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4312;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4313;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4358;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4359;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4360;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4361;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4362;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4579;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4580;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4583;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4585;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4654;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4655;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4656;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4659;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4660;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4661;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4665;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4667;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4668;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4669;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4670;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4671;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4672;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4673;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4674;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4675;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4676;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4677;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4679;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4680;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4681;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4683;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4684;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4685;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4686;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4687;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4688;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4689;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4690;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4691;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4692;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4693;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4694;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4695;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4696;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4697;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4698;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4699;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4700;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4701;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4702;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4703;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4704;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4705;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4707;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4708;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4709;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4710;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4711;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4720;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4724;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4734;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4865;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4866;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4867;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4868;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4869;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4870;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4871;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4872;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4873;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4874;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4875;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4876;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4987;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 5137;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3765, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3773, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3776, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3777, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3779, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3780, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3783, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3785, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3786, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3787, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3788, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3789, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3790, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3791, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3792, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3793, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3795, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3796, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3797, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3798, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3800, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3806, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3807, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3809, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3812, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3848, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4290, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4292, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4309, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4310, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4311, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4312, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4313, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4358, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4359, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4360, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4361, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4362, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4579, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4580, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4583, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4585, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4654, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4655, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4656, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4659, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4660, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4661, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4665, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4667, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4668, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4669, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4670, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4671, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4672, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4673, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4674, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4675, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4676, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4677, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4679, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4680, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4681, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4683, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4684, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4685, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4686, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4687, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4688, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4689, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4690, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4691, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4692, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4693, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4694, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4695, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4696, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4697, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4698, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4699, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4700, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4701, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4702, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4703, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4704, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4705, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4707, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4708, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4709, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4710, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4711, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4720, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4724, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4734, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4865, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4866, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4867, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4868, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4869, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4870, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4871, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4872, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4873, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4874, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4875, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4876, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4987, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5137, 40) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 40;
