UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6716;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6717;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6718;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6719;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6720;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6721;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6722;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6723;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6724;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6725;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6726;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6727;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6728;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6729;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6730;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6731;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6716, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6717, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6718, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6719, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6720, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6721, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6722, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6723, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6724, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6725, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6726, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6727, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6728, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6729, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6730, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6731, 16) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 16;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6716, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6717, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6718, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6719, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6720, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6721, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6722, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6723, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6724, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6725, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6726, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6727, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6728, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6729, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6730, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6731, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
