UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 23068;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 44466;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 50143;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 50146;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68659;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68664;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68682;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68683;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68684;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68685;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68686;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68687;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68688;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68689;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68690;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68691;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68693;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68738;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 68749;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 88480;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 88483;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 88677;
UPDATE peralatan_mesin SET id_sub_skpd = 433 WHERE id = 89800;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23068;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44466;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50143;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50146;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68659;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68664;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68682;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68683;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68684;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68685;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68686;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68687;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68688;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68689;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68690;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68691;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68693;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68738;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68749;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88480;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88483;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88677;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89800;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23068, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44466, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50143, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50146, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68659, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68664, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68682, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68683, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68684, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68685, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68686, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68687, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68688, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68689, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68690, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68691, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68693, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68738, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68749, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88480, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88483, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88677, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89800, 48) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 48;
