-- Pariwisata ke Dinas Pemuda
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 100741;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 112735;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 15719;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 15721;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 2217;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 2512;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 275;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 318;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 33746;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3418;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3420;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 34464;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3471;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3473;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3498;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3590;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3720;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3722;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3725;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3774;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3775;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3776;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3778;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3780;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3786;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3795;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3827;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3861;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3862;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3866;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 4379;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44366;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44380;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44381;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44382;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44383;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44385;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44386;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44387;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44389;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44390;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44391;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44392;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44394;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44396;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44397;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44398;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44400;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44401;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44403;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44404;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44405;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44406;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44407;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44408;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44420;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44421;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44422;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44423;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44424;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44425;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44440;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44512;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 4762;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 50097;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 50098;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 50099;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 50100;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5093;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5110;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5147;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5214;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5271;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 52818;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5303;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5338;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 562;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 67125;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 67127;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 67128;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68046;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68053;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68056;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68059;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68070;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68106;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68118;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68131;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68142;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68146;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68152;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 68209;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 69234;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 69235;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 69236;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 69237;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 69238;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 69239;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87278;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87279;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87281;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87282;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87284;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87285;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87286;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87287;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87288;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87289;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87290;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87292;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87293;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87314;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87784;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87785;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87786;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87787;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87788;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87789;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 87897;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97464;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97465;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97466;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97469;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97796;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97798;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97841;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 97845;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 98117;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 99428;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 99429;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 15399;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 2529;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 280;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 2803;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3067;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 3081;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 34462;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 41771;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44367;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 44426;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 4725;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 4948;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 50096;
UPDATE peralatan_mesin SET id_sub_skpd = 438 WHERE id = 5252;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100741;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112735;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15719;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15721;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2217;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2512;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 275;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 318;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33746;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3418;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3420;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34464;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3471;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3473;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3498;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3590;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3720;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3722;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3725;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3774;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3775;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3776;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3778;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3780;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3786;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3795;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3827;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3861;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3862;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3866;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4379;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44366;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44380;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44381;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44382;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44383;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44385;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44386;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44387;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44389;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44390;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44391;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44392;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44394;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44396;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44397;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44398;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44400;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44401;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44403;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44404;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44405;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44406;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44407;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44408;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44420;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44421;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44422;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44423;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44424;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44425;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44440;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44512;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4762;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50097;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50098;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50099;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50100;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5110;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5147;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5214;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5271;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52818;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5303;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5338;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 562;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 67125;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 67127;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 67128;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68046;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68053;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68056;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68059;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68070;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68106;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68118;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68131;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68142;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68146;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68152;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68209;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69234;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69235;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69236;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69237;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69238;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69239;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87278;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87279;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87281;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87282;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87284;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87285;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87286;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87287;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87288;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87289;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87290;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87292;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87293;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87314;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87784;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87785;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87786;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87787;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87788;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87789;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87897;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97464;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97465;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97466;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97469;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97796;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97798;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97841;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97845;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98117;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99428;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99429;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15399;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2529;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 280;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2803;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3067;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3081;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34462;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 41771;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44367;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44426;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4725;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4948;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50096;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5252;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100741, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112735, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15719, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15721, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2217, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2512, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (275, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (318, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33746, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3418, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3420, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34464, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3471, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3473, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3498, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3590, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3720, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3722, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3725, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3774, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3775, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3776, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3778, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3780, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3786, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3795, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3827, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3861, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3862, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3866, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4379, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44366, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44380, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44381, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44382, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44383, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44385, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44386, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44387, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44389, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44390, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44391, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44392, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44394, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44396, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44397, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44398, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44400, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44401, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44403, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44404, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44405, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44406, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44407, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44408, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44420, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44421, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44422, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44423, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44424, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44425, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44440, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44512, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4762, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50097, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50098, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50099, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50100, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5093, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5110, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5147, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5214, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5271, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52818, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5303, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5338, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (562, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (67125, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (67127, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (67128, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68046, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68053, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68056, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68059, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68070, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68106, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68118, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68131, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68142, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68146, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68152, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68209, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69234, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69235, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69236, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69237, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69238, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69239, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87278, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87279, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87281, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87282, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87284, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87285, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87286, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87287, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87288, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87289, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87290, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87292, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87293, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87314, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87784, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87785, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87786, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87787, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87788, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87789, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87897, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97464, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97465, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97466, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97469, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97796, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97798, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97841, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97845, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98117, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99428, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99429, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15399, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2529, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (280, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2803, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3067, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3081, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34462, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (41771, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44367, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44426, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4725, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4948, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50096, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5252, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
