UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 12;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 2719;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3015;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3208;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3223;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3407;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3698;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3760;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3761;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3762;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3763;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3764;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3765;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3766;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3767;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3768;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3786;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 3787;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 526;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 531;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 533;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 605;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 6131;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 6133;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 6138;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 6164;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 6293;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 745;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 746;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 747;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 749;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 75;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 753;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 754;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 755;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 756;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 757;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 759;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 761;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 762;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 763;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 764;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 765;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 766;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 767;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 789;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 797;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 798;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 847;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 860;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 875;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 877;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 878;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 793;
UPDATE gedung_bangunan SET id_sub_skpd = 71 WHERE id = 751;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 12;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 2719;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3015;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3208;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3223;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3407;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3698;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3760;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3761;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3762;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3763;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3764;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3765;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3766;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3767;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3768;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3786;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 3787;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 526;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 531;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 533;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 605;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6131;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6133;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6138;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6164;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 6293;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 745;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 746;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 747;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 749;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 75;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 753;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 754;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 755;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 756;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 757;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 759;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 761;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 762;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 763;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 764;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 765;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 766;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 767;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 789;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 797;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 798;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 847;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 860;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 875;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 877;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 878;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 793;
UPDATE harga_gedung_bangunan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_gedung_bangunan = 751;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (12, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (2719, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3015, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3208, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3223, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3407, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3698, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3760, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3761, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3762, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3763, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3764, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3765, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3766, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3767, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3768, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3786, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (3787, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (526, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (531, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (533, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (605, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6131, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6133, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6138, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6164, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6293, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (745, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (746, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (747, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (749, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (75, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (753, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (754, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (755, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (756, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (757, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (759, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (761, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (762, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (763, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (764, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (765, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (766, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (767, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (789, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (797, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (798, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (847, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (860, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (875, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (877, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (878, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (793, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (751, 45) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 45;
