INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.01.01','ALAT BESAR DARAT');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.01.02','ALAT BESAR APUNG');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.01.03','ALAT BANTU');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.02.01','ALAT ANGKUTAN DARAT BERMOTOR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.02.02','ALAT ANGKUTAN DARAT TAK BERMOTOR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.02.03','ALAT ANGKUTAN APUNG BERMOTOR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.02.04','ALAT ANGKUTAN APUNG TAK BERMOTOR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.02.05','ALAT ANGKUTAN BERMOTOR UDARA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.03.01','ALAT BENGKEL BERMESIN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.03.02','ALAT BENGKEL TAK BERMESIN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.03.03','ALAT UKUR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.04.01','ALAT PENGOLAHAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.05.01','ALAT KANTOR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.05.02','ALAT RUMAH TANGGA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.05.03','MEJA DAN KURSI KERJA/RAPAT PEJABAT');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.06.01','ALAT STUDIO');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.06.02','ALAT KOMUNIKASI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.06.03','PERALATAN PEMANCAR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.06.04','PERALATAN KOMUNIKASI NAVIGASI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.07.01','ALAT KEDOKTERAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.07.02','ALAT KESEHATAN UMUM');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.01','UNIT ALAT LABORATORIUM');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.02','UNIT ALAT LABORATORIUM KIMIA NUKLIR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.03','ALAT PERAGA PRAKTEK SEKOLAH');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.04','ALAT LABORATORIUM FISIKA NUKLIR/ELEKTRONIKA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.05','ALAT PROTEKSI RADIASI/PROTEKSI LINGKUNGAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.06','DESTRUCTIVE TESTING LABORATORY');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.07','ALAT LABORATORIUM LINGKUNGAN HIDUP');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.08','PERALATAN LABORATORIUM HYDRODINAMICA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.08.09','ALAT LABORATORIUM STANDARISASI KALIBRASI DAN INSTRUMENTASI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.09.01','SENJATA API');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.09.02','PERSENJATAAN NON SENJATA API');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.09.03','SENJATA SINAR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.09.04','ALAT KHUSUS KEPOLISIAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.10.01','KOMPUTER UNIT');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.10.02','PERALATAN KOMPUTER');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.11.01','ALAT EKSPLORASI TOPOGRAFI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.11.02','ALAT EKSPLORASI GEOFISIKA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.12.01','ALAT PENGEBORAN MESIN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.12.02','ALAT PENGEBORAN NON MESIN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.13.01','SUMUR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.13.02','PRODUKSI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.13.03','PENGOLAHAN DAN PEMURNIAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.14.01','ALAT BANTU EKSPLORASI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.14.02','ALAT BANTU PRODUKSI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.15.01','ALAT DETEKSI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.15.02','ALAT PELINDUNG');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.15.03','ALAT SAR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.15.04','ALAT KERJA PENERBANGAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.16.01','ALAT PERAGA PELATIHAN DANPERCONTOHAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.17.01','UNIT PERALATAN PROSES/PRODUKSI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.18.01','RAMBU-RAMBU LALU LINTAS DARAT');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.18.02','RAMBU-RAMBU LALU LINTAS UDARA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.18.03','RAMBU-RAMBU LALU LINTAS LAUT');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.2.19.01','PERALATAN OLAH RAGA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.3.01.01','BANGUNAN GEDUNG TEMPAT KERJA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.3.01.02','BANGUNAN GEDUNG TEMPAT TINGGAL');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.3.02.01','CANDI/TUGU PERINGATAN/PRASASTI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.3.03.01','BANGUNAN MENARA PERAMBUAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.3.04.01','TUGU/TANDA BATAS');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.01.01','JALAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.01.02','JEMBATAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.02.01','BANGUNAN AIR IRIGASI');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.02.02','BANGUNAN PENGAIRAN PASANGSURUT');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.02.03','BANGUNAN PENGEMBANGAN RAWADAN POLDER');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.02.04','BANGUNAN PENGAMAN SUNGAI/PANTAI & PENANGGULANGAN BENCANA ALAM');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.02.05','BANGUNAN PENGEMBANGAN SUMBER AIR DAN AIR TANAH');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.02.06','BANGUNAN AIR BERSIH/AIR BAKU');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.02.07','BANGUNAN AIR KOTOR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.01','INSTALASI AIR BERSIH/AIR BAKU');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.02','INSTALASI AIR KOTOR');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.03','INSTALASI PENGOLAHAN SAMPAH');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.04','INSTALASI PENGOLAHAN BAHAN BANGUNAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.05','INSTALASI PEMBANGKIT LISTRIK');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.06','INSTALASI GARDU LISTRIK');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.07','INSTALASI PERTAHANAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.08','INSTALASI GAS');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.09','INSTALASI PENGAMAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.03.10','INSTALASI LAIN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.04.01','JARINGAN AIR MINUM');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.04.02','JARINGAN LISTRIK');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.04.03','JARINGAN TELEPON');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.4.04.04','JARINGAN GAS');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.01.01','BAHAN PERPUSTAKAAN TERCETAK');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.01.02','BAHAN PERPUSTAKAAN TEREKAM DANBENTUK MIKRO');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.01.03','KARTOGRAFI, NASKAH DAN LUKISAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.01.04','MUSIK');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.01.05','KARYA GRAFIKA (GRAPHIC MATERIAL)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.01.06','THREE DIMENSIONAL ARTEFACS ANDREALITA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.01.07','TARSCALT');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.02.01','BARANG BERCORAK KESENIAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.02.02','ALAT BERCORAK KEBUDAYAAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.02.03','TANDA PENGHARGAAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.03.01','HEWAN PIARAAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.03.02','TERNAK');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.03.03','HEWAN LAINNYA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.01','IKAN BERSIRIP (PISCES/IKANBERSIRIP)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.02','CRUSTEA (UDANG, RAJUNGAN,KEPITING, DAN SEBANGSANYA)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.03','MOLLUSCA (KERANG, TIRAM, CUMI- CUMI, GURITA, SIPUT, DAN SEBANGSANYA)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.04','COELENTERATA (UBUR-UBUR DANSEBANGSANYA)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.05','ECHINODERMATA (TRIPANG, BULUBABI, DAN SEBANGSANYA)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.06','AMPHIBIA (KODOK DANSEBANGSANYA)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.07','REPTILIA (BUAYA, PENYU, KURA-KURA, BIAWAK, ULAR AIR, DAN SEBANGSANYA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.08','MAMMALIA (PAUS, LUMBA-LUMBA,PESUT, DUYUNG, DAN SEBANGSANYA)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.09','ALGAE (RUMPUT LAUT DAN TUMBUH- TUMBUHAN LAIN YANG HIDUP DI DALAM AIR)');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.04.10','BIOTA PERAIRAN LAINNYA');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.05.01','TANAMAN');
INSERT INTO kelompok_barang_108 (kode_kelompok_barang, nama_kelompok_barang) VALUES ('1.3.5.06.01','BARANG KOLEKSI NON BUDAYA');
