UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118184;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118185;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118186;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118187;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118188;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118189;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118190;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118191;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118192;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118193;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118194;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118195;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118196;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118197;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118198;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118199;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118200;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118201;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118202;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118203;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118204;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118205;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118206;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118207;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118208;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118209;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118210;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118211;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118212;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118213;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118214;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118215;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118216;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118217;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118218;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118219;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118220;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118221;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118222;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118223;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118224;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118225;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118226;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118227;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118228;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118229;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118230;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118231;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118232;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118233;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118234;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118235;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118236;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118237;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118238;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118239;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118240;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118241;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118242;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118243;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118244;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118245;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118246;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118247;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118248;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118249;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118250;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118251;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118252;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118253;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118254;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118255;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118256;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118257;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118258;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118259;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118260;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118261;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118184, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118185, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118186, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118187, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118188, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118189, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118190, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118191, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118192, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118193, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118194, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118195, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118196, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118197, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118198, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118199, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118200, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118201, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118202, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118203, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118204, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118205, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118206, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118207, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118208, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118209, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118210, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118211, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118212, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118213, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118214, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118215, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118216, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118217, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118218, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118219, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118220, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118221, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118222, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118223, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118224, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118225, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118226, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118227, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118228, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118229, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118230, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118231, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118232, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118233, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118234, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118235, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118236, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118237, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118238, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118239, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118240, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118241, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118242, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118243, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118244, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118245, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118246, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118247, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118248, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118249, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118250, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118251, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118252, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118253, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118254, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118255, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118256, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118257, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118258, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118259, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118260, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118261, 2) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 2;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118184, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118185, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118186, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118187, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118188, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118189, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118190, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118191, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118192, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118193, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118194, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118195, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118196, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118197, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118198, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118199, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118200, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118201, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118202, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118203, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118204, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118205, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118206, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118207, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118208, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118209, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118210, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118211, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118212, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118213, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118214, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118215, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118216, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118217, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118218, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118219, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118220, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118221, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118222, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118223, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118224, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118225, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118226, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118227, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118228, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118229, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118230, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118231, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118232, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118233, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118234, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118235, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118236, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118237, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118238, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118239, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118240, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118241, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118242, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118243, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118244, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118245, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118246, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118247, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118248, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118249, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118250, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118251, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118252, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118253, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118254, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118255, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118256, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118257, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118258, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118259, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118260, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118261, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
