from peralatanmesin.models import PeralatanMesin
from gedungbangunan.clone_object import clone_object

def pm_litbang_ke_dinas_pertanahan():
    clone_object(PeralatanMesin.objects.get(pk=23068))
    clone_object(PeralatanMesin.objects.get(pk=44466))
    clone_object(PeralatanMesin.objects.get(pk=50143))
    clone_object(PeralatanMesin.objects.get(pk=50146))
    clone_object(PeralatanMesin.objects.get(pk=68659))
    clone_object(PeralatanMesin.objects.get(pk=68664))
    clone_object(PeralatanMesin.objects.get(pk=68682))
    clone_object(PeralatanMesin.objects.get(pk=68683))
    clone_object(PeralatanMesin.objects.get(pk=68684))
    clone_object(PeralatanMesin.objects.get(pk=68685))
    clone_object(PeralatanMesin.objects.get(pk=68686))
    clone_object(PeralatanMesin.objects.get(pk=68687))
    clone_object(PeralatanMesin.objects.get(pk=68688))
    clone_object(PeralatanMesin.objects.get(pk=68689))
    clone_object(PeralatanMesin.objects.get(pk=68690))
    clone_object(PeralatanMesin.objects.get(pk=68691))
    clone_object(PeralatanMesin.objects.get(pk=68693))
    clone_object(PeralatanMesin.objects.get(pk=68738))
    clone_object(PeralatanMesin.objects.get(pk=68749))
    clone_object(PeralatanMesin.objects.get(pk=88480))
    clone_object(PeralatanMesin.objects.get(pk=88483))
    clone_object(PeralatanMesin.objects.get(pk=88677))
    clone_object(PeralatanMesin.objects.get(pk=89800))
