UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119608;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119609;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119610;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119611;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119612;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119613;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119614;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119615;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119616;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119617;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119618;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119619;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119620;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119621;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119622;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119623;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119624;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119625;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119626;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119627;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119628;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119629;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 119630;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119608, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119609, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119610, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119611, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119612, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119613, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119614, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119615, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119616, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119617, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119618, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119619, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119620, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119621, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119622, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119623, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119624, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119625, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119626, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119627, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119628, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119629, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (119630, 4) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 4;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119608, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119609, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119610, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119611, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119612, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119613, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119614, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119615, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119616, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119617, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119618, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119619, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119620, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119621, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119622, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119623, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119624, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119625, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119626, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119627, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119628, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119629, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (119630, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
