cat atl_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > atl_setda.sql
cat atl_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > atl_dispu.sql
cat atl_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > atl_dishub.sql
cat atl_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > atl_dinkes.sql
cat atl_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"id_skpd = 1"/"id_skpd = 6"/g > atl_rsud.sql
cat atl_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > atl_disdik.sql
cat atl_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > atl_kpdad.sql
cat atl_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > atl_snt.sql
cat atl_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > atl_bpmpd.sql
cat atl_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > atl_bppakb.sql
cat atl_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > atl_dukcatpil.sql
cat atl_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > atl_pertanian.sql
cat atl_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 14"/g > atl_kehutanan.sql
cat atl_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > atl_bppkp.sql
cat atl_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > atl_perindagkop.sql
cat atl_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"id_skpd = 1"/"id_skpd = 17"/g > atl_distamben.sql
cat atl_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > atl_kp2tpm.sql
cat atl_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > atl_dppkad.sql
cat atl_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > atl_inspektorat.sql
cat atl_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > atl_bappeda.sql
cat atl_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > atl_blhk.sql
cat atl_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > atl_disporaparbud.sql
cat atl_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > atl_kesbangpol.sql
cat atl_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > atl_satpolpp.sql
cat atl_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > atl_bkd.sql
cat atl_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"id_skpd = 1"/"id_skpd = 27"/g > atl_korpri.sql
cat atl_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > atl_paringin.sql
cat atl_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"id_skpd = 1"/"id_skpd = 29"/g > atl_paringinkota.sql
cat atl_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"id_skpd = 1"/"id_skpd = 30"/g > atl_paringintimur.sql
cat atl_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > atl_lampihong.sql
cat atl_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > atl_batumandi.sql
cat atl_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > atl_juai.sql
cat atl_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > atl_awayan.sql
cat atl_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > atl_halong.sql
cat atl_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > atl_paringinselatan.sql
cat atl_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"id_skpd = 1"/"id_skpd = 37"/g > atl_batupiring.sql
cat atl_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > atl_tebingtinggi.sql
cat atl_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > atl_bpbd.sql
cat atl_setwan.sql | sed -e s/setwan/b40/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > atl_b40.sql
cat atl_setwan.sql | sed -e s/setwan/b41/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > atl_b41.sql
cat atl_setwan.sql | sed -e s/setwan/b42/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > atl_b42.sql
cat atl_setwan.sql | sed -e s/setwan/b43/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > atl_b43.sql
cat atl_setwan.sql | sed -e s/setwan/b44/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > atl_b44.sql
cat atl_setwan.sql | sed -e s/setwan/b45/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > atl_b45.sql
cat atl_setwan.sql | sed -e s/setwan/b46/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > atl_b46.sql
cat atl_setwan.sql | sed -e s/setwan/b47/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > atl_b47.sql
cat atl_setwan.sql | sed -e s/setwan/b48/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > atl_b48.sql

cat atl_*.sql > ../gabungan_atl.sql
