UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28772;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28773;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28774;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28776;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28777;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28778;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28779;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28781;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28782;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28783;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28784;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28830;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28832;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28833;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28834;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28838;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28841;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28843;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28844;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28845;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28846;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28847;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28848;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 28849;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 52028;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 71070;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88871;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88873;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88874;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88875;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88882;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88883;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88884;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88891;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88892;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88893;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88898;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88908;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88909;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88910;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88911;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88912;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88913;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88914;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 88915;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89759;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89760;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89761;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89762;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89763;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89764;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89955;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 89956;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99266;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99385;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99386;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99387;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99388;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99389;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99393;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99394;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99395;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99396;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99410;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99411;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99412;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99413;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99414;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99415;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99416;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99417;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99418;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99419;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99433;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99436;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99437;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99438;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99466;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99467;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99468;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99469;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99470;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99471;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99472;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99473;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99474;
UPDATE peralatan_mesin SET id_sub_skpd = 403 WHERE id = 99475;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28772;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28773;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28774;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28776;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28777;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28778;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28779;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28781;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28782;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28783;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28784;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28830;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28832;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28833;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28834;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28838;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28841;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28843;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28844;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28845;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28846;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28847;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28848;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 28849;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52028;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71070;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88871;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88873;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88874;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88875;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88882;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88883;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88884;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88891;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88892;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88893;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88898;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88908;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88909;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88910;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88911;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88912;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88913;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88914;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88915;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89759;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89760;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89761;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89762;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89763;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89764;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89955;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89956;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99266;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99385;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99386;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99387;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99388;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99389;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99393;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99394;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99395;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99396;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99410;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99411;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99412;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99413;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99414;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99415;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99416;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99417;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99418;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99419;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99433;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99436;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99437;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99438;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99466;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99467;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99468;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99469;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99470;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99471;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99472;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99473;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99474;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99475;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28772, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28773, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28774, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28776, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28777, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28778, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28779, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28781, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28782, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28783, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28784, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28830, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28832, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28833, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28834, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28838, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28841, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28843, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28844, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28845, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28846, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28847, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28848, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (28849, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52028, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71070, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88871, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88873, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88874, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88875, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88882, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88883, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88884, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88891, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88892, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88893, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88898, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88908, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88909, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88910, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88911, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88912, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88913, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88914, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88915, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89759, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89760, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89761, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89762, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89763, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89764, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89955, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89956, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99266, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99385, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99386, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99387, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99388, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99389, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99393, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99394, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99395, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99396, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99410, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99411, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99412, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99413, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99414, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99415, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99416, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99417, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99418, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99419, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99433, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99436, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99437, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99438, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99466, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99467, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99468, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99469, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99470, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99471, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99472, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99473, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99474, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99475, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
