UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117756;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117757;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117758;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117759;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117760;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117761;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117762;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117763;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117764;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117765;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117766;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117767;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117768;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117769;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117770;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117771;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117772;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117773;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117774;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117775;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117776;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117777;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117778;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117779;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117780;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117781;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117782;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117783;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117784;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117785;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117786;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117787;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117788;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117789;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117790;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117791;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117792;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117793;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117794;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117795;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117796;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117797;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117798;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117799;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117800;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117801;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117802;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117803;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117804;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117805;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117806;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117807;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117808;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117809;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117810;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117811;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117812;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117813;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117814;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117815;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117816;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117817;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117818;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117819;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117820;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117821;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117822;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117823;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117824;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117825;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117826;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117827;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117828;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117829;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117830;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117831;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117832;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117833;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117834;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117835;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117836;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117837;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117838;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117839;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117840;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117841;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117842;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117756, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117757, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117758, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117759, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117760, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117761, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117762, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117763, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117764, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117765, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117766, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117767, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117768, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117769, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117770, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117771, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117772, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117773, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117774, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117775, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117776, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117777, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117778, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117779, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117780, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117781, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117782, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117783, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117784, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117785, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117786, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117787, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117788, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117789, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117790, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117791, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117792, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117793, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117794, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117795, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117796, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117797, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117798, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117799, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117800, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117801, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117802, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117803, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117804, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117805, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117806, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117807, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117808, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117809, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117810, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117811, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117812, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117813, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117814, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117815, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117816, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117817, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117818, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117819, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117820, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117821, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117822, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117823, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117824, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117825, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117826, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117827, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117828, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117829, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117830, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117831, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117832, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117833, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117834, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117835, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117836, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117837, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117838, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117839, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117840, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117841, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117842, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117756, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117757, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117758, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117759, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117760, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117761, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117762, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117763, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117764, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117765, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117766, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117767, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117768, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117769, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117770, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117771, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117772, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117773, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117774, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117775, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117776, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117777, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117778, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117779, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117780, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117781, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117782, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117783, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117784, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117785, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117786, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117787, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117788, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117789, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117790, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117791, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117792, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117793, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117794, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117795, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117796, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117797, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117798, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117799, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117800, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117801, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117802, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117803, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117804, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117805, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117806, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117807, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117808, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117809, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117810, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117811, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117812, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117813, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117814, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117815, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117816, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117817, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117818, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117819, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117820, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117821, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117822, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117823, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117824, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117825, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117826, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117827, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117828, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117829, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117830, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117831, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117832, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117833, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117834, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117835, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117836, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117837, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117838, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117839, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117840, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117841, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117842, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
