cat gedung_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"skpd.id = 1"/"skpd.id = 2"/g > gedung_setda.sql
cat gedung_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"skpd.id = 1"/"skpd.id = 3"/g > gedung_dpupr.sql
cat gedung_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"skpd.id = 1"/"skpd.id = 4"/g > gedung_dishub.sql
cat gedung_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"skpd.id = 1"/"skpd.id = 5"/g > gedung_dinkes.sql
cat gedung_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"skpd.id = 1"/"skpd.id = 6"/g > gedung_rsud.sql
cat gedung_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"skpd.id = 1"/"skpd.id = 7"/g > gedung_disdik.sql
cat gedung_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"skpd.id = 1"/"skpd.id = 8"/g > gedung_perpustakaan.sql
cat gedung_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"skpd.id = 1"/"skpd.id = 9"/g > gedung_sosial.sql
cat gedung_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"skpd.id = 1"/"skpd.id = 10"/g > gedung_dpmd.sql
cat gedung_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"skpd.id = 1"/"skpd.id = 11"/g > gedung_dpppa.sql
cat gedung_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"skpd.id = 1"/"skpd.id = 12"/g > gedung_dukcatpil.sql
cat gedung_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"skpd.id = 1"/"skpd.id = 13"/g > gedung_pertanian.sql
cat gedung_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"skpd.id = 1"/"skpd.id = 14"/g > gedung_kehutanan.sql
cat gedung_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"skpd.id = 1"/"skpd.id = 15"/g > gedung_dkp.sql
cat gedung_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"skpd.id = 1"/"skpd.id = 16"/g > gedung_dkukmp.sql
cat gedung_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"skpd.id = 1"/"skpd.id = 17"/g > gedung_distamben.sql
cat gedung_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"skpd.id = 1"/"skpd.id = 18"/g > gedung_dpmptsp.sql
cat gedung_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"skpd.id = 1"/"skpd.id = 19"/g > gedung_bkd.sql
cat gedung_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"skpd.id = 1"/"skpd.id = 20"/g > gedung_inspektorat.sql
cat gedung_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"skpd.id = 1"/"skpd.id = 21"/g > gedung_bappeda.sql
cat gedung_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"skpd.id = 1"/"skpd.id = 22"/g > gedung_dlh.sql
cat gedung_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"skpd.id = 1"/"skpd.id = 23"/g > gedung_dko.sql
cat gedung_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"skpd.id = 1"/"skpd.id = 24"/g > gedung_kesbangpol.sql
cat gedung_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"skpd.id = 1"/"skpd.id = 25"/g > gedung_satpolpp.sql
cat gedung_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"skpd.id = 1"/"skpd.id = 26"/g > gedung_bkppd.sql
cat gedung_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"skpd.id = 1"/"skpd.id = 27"/g > gedung_korpri.sql
cat gedung_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"skpd.id = 1"/"skpd.id = 28"/g > gedung_paringin.sql
cat gedung_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"skpd.id = 1"/"skpd.id = 29"/g > gedung_paringinkota.sql
cat gedung_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"skpd.id = 1"/"skpd.id = 30"/g > gedung_paringintimur.sql
cat gedung_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"skpd.id = 1"/"skpd.id = 31"/g > gedung_lampihong.sql
cat gedung_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"skpd.id = 1"/"skpd.id = 32"/g > gedung_batumandi.sql
cat gedung_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"skpd.id = 1"/"skpd.id = 33"/g > gedung_juai.sql
cat gedung_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"skpd.id = 1"/"skpd.id = 34"/g > gedung_awayan.sql
cat gedung_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"skpd.id = 1"/"skpd.id = 35"/g > gedung_halong.sql
cat gedung_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"skpd.id = 1"/"skpd.id = 36"/g > gedung_paringinselatan.sql
cat gedung_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"skpd.id = 1"/"skpd.id = 37"/g > gedung_batupiring.sql
cat gedung_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"skpd.id = 1"/"skpd.id = 38"/g > gedung_tebingtinggi.sql
cat gedung_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"skpd.id = 1"/"skpd.id = 39"/g > gedung_bpbd.sql
cat gedung_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"skpd.id = 1"/"skpd.id = 40"/g > gedung_dpkp.sql
cat gedung_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"skpd.id = 1"/"skpd.id = 41"/g > gedung_disnakertrans.sql
cat gedung_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"skpd.id = 1"/"skpd.id = 42"/g > gedung_dppkb.sql
cat gedung_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"skpd.id = 1"/"skpd.id = 43"/g > gedung_kominfo.sql
cat gedung_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"skpd.id = 1"/"skpd.id = 44"/g > gedung_kearsipan.sql
cat gedung_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"skpd.id = 1"/"skpd.id = 45"/g > gedung_perikanan.sql
cat gedung_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"skpd.id = 1"/"skpd.id = 46"/g > gedung_pariwisata.sql
cat gedung_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"skpd.id = 1"/"skpd.id = 47"/g > gedung_perdagangan.sql
cat gedung_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"skpd.id = 1"/"skpd.id = 48"/g > gedung_bppd.sql

cat gedung_*.sql > ../gabungan_gedung.sql
