-- Pariwisata ke Dinas Pemuda
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113525;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113526;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113527;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113528;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113529;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113530;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113531;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113532;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113533;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113534;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113535;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113536;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113537;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113538;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113539;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113540;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113541;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113542;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113543;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113544;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113545;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113546;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113547;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113548;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113549;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113550;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113551;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113552;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113553;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113554;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113555;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113556;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113557;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113558;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113559;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113560;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113561;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113562;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113563;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113564;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113565;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113566;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113567;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113568;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113569;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113570;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113571;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113572;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113573;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113574;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113575;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113576;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113577;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113578;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113579;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113580;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113581;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113582;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113583;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113584;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113585;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113586;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113587;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113588;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113589;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113590;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113591;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113592;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113593;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113594;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113595;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113596;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113597;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113598;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113599;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113600;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113601;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113602;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113603;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113604;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113605;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113606;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113607;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113608;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113609;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113610;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113611;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113612;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113613;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113614;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113615;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113616;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113617;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113618;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113619;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113620;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113621;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113622;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113623;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113624;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113625;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113626;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113627;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113628;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113629;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113630;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113631;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113632;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113633;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113634;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113635;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113636;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113637;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113638;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113639;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113640;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113641;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113642;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113643;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113644;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113645;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113646;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113647;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113648;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113649;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113650;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113651;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113652;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113653;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113654;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113655;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113656;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113657;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113658;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113659;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113660;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113661;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113662;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113663;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113664;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113665;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113666;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113667;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 113668;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113525, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113526, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113527, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113528, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113529, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113530, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113531, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113532, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113533, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113534, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113535, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113536, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113537, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113538, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113539, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113540, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113541, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113542, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113543, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113544, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113545, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113546, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113547, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113548, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113549, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113550, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113551, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113552, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113553, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113554, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113555, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113556, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113557, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113558, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113559, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113560, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113561, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113562, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113563, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113564, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113565, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113566, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113567, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113568, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113569, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113570, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113571, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113572, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113573, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113574, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113575, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113576, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113577, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113578, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113579, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113580, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113581, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113582, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113583, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113584, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113585, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113586, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113587, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113588, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113589, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113590, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113591, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113592, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113593, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113594, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113595, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113596, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113597, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113598, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113599, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113600, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113601, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113602, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113603, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113604, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113605, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113606, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113607, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113608, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113609, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113610, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113611, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113612, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113613, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113614, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113615, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113616, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113617, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113618, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113619, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113620, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113621, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113622, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113623, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113624, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113625, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113626, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113627, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113628, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113629, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113630, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113631, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113632, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113633, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113634, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113635, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113636, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113637, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113638, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113639, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113640, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113641, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113642, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113643, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113644, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113645, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113646, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113647, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113648, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113649, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113650, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113651, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113652, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113653, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113654, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113655, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113656, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113657, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113658, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113659, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113660, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113661, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113662, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113663, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113664, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113665, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113666, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113667, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (113668, 23) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 23;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113525, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113526, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113527, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113528, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113529, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113530, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113531, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113532, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113533, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113534, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113535, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113536, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113537, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113538, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113539, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113540, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113541, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113542, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113543, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113544, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113545, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113546, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113547, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113548, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113549, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113550, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113551, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113552, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113553, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113554, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113555, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113556, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113557, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113558, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113559, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113560, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113561, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113562, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113563, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113564, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113565, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113566, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113567, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113568, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113569, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113570, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113571, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113572, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113573, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113574, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113575, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113576, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113577, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113578, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113579, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113580, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113581, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113582, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113583, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113584, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113585, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113586, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113587, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113588, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113589, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113590, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113591, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113592, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113593, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113594, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113595, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113596, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113597, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113598, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113599, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113600, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113601, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113602, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113603, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113604, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113605, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113606, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113607, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113608, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113609, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113610, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113611, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113612, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113613, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113614, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113615, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113616, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113617, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113618, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113619, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113620, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113621, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113622, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113623, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113624, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113625, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113626, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113627, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113628, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113629, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113630, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113631, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113632, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113633, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113634, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113635, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113636, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113637, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113638, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113639, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113640, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113641, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113642, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113643, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113644, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113645, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113646, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113647, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113648, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113649, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113650, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113651, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113652, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113653, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113654, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113655, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113656, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113657, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113658, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113659, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113660, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113661, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113662, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113663, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113664, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113665, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113666, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113667, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (113668, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
