UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 1037;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 2759;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 2886;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 2887;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 3922;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 3930;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4136;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4137;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4138;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4850;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4903;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4925;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4926;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4927;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4928;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4929;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 4930;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 849;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 854;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 857;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 862;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 864;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 868;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 871;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 878;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 882;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 883;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 893;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 898;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 899;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 863;
UPDATE jalan_irigasi_jaringan SET id_sub_skpd = 71 WHERE id = 876;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 1037;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 2759;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 2886;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 2887;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3922;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 3930;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4136;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4137;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4138;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4850;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4903;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4925;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4926;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4927;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4928;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4929;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 4930;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 849;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 854;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 857;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 862;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 864;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 868;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 871;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 878;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 882;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 883;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 893;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 898;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 899;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 863;
UPDATE harga_jalan_irigasi_jaringan SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_jalan_irigasi_jaringan = 876;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (1037, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (2759, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (2886, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (2887, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3922, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (3930, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4136, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4137, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4138, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4850, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4903, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4925, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4926, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4927, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4928, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4929, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (4930, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (849, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (854, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (857, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (862, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (864, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (868, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (871, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (878, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (882, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (883, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (893, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (898, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (899, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (863, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
INSERT INTO skpd_asal_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (876, 45) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 45;
