UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117549;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117550;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117551;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117552;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117553;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117554;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117555;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117556;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117557;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117558;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117559;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117560;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117561;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117562;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117563;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117564;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117565;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117566;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117567;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117568;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117569;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117570;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117571;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117572;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117573;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117574;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117575;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117576;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117577;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117578;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117579;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117580;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117581;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117582;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117583;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117584;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117585;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117586;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117587;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117588;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117589;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117590;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117591;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117592;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117593;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117594;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117595;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117596;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117597;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117598;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117599;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117600;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117601;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117602;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117603;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117604;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117605;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117606;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117607;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117608;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117609;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117610;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117611;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117612;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117613;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117614;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117615;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117616;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117617;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117618;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117619;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117620;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117621;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117622;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117623;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117624;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117625;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117626;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117627;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117628;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117629;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117630;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117631;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117632;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117633;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117634;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117635;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117636;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117637;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117638;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117639;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117640;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117641;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117642;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117643;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117644;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117645;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117646;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117647;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117648;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117649;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117650;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117651;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117652;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117653;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117654;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117655;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117656;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117657;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117658;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117659;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117660;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117661;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117662;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117663;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117664;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117665;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117666;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117667;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117668;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117669;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117670;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117671;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117672;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117673;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117674;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117675;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117676;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117677;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117678;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117679;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117680;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117681;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117682;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117683;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117684;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117685;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117686;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117687;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117688;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117689;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117690;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117691;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117692;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117693;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117694;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117695;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117696;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117697;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117698;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117699;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117700;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117701;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117702;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117703;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117704;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117705;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117706;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117707;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117708;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117709;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117710;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117711;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117712;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117713;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117714;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117715;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117716;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117717;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117718;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117719;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117720;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117721;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117722;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117723;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117724;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117725;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117726;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117727;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117728;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117729;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117730;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117731;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117732;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117733;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117734;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117735;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117736;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117737;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117738;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117739;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117740;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117741;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117742;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117743;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117744;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117745;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117746;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117747;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117748;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117749;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117750;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117751;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117752;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117753;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117754;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 117755;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117549, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117550, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117551, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117552, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117553, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117554, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117555, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117556, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117557, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117558, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117559, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117560, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117561, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117562, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117563, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117564, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117565, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117566, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117567, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117568, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117569, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117570, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117571, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117572, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117573, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117574, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117575, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117576, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117577, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117578, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117579, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117580, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117581, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117582, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117583, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117584, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117585, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117586, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117587, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117588, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117589, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117590, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117591, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117592, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117593, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117594, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117595, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117596, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117597, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117598, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117599, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117600, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117601, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117602, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117603, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117604, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117605, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117606, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117607, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117608, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117609, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117610, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117611, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117612, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117613, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117614, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117615, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117616, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117617, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117618, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117619, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117620, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117621, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117622, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117623, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117624, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117625, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117626, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117627, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117628, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117629, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117630, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117631, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117632, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117633, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117634, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117635, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117636, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117637, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117638, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117639, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117640, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117641, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117642, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117643, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117644, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117645, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117646, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117647, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117648, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117649, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117650, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117651, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117652, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117653, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117654, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117655, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117656, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117657, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117658, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117659, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117660, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117661, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117662, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117663, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117664, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117665, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117666, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117667, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117668, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117669, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117670, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117671, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117672, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117673, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117674, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117675, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117676, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117677, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117678, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117679, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117680, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117681, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117682, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117683, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117684, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117685, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117686, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117687, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117688, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117689, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117690, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117691, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117692, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117693, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117694, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117695, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117696, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117697, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117698, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117699, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117700, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117701, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117702, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117703, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117704, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117705, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117706, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117707, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117708, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117709, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117710, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117711, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117712, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117713, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117714, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117715, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117716, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117717, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117718, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117719, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117720, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117721, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117722, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117723, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117724, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117725, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117726, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117727, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117728, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117729, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117730, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117731, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117732, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117733, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117734, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117735, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117736, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117737, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117738, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117739, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117740, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117741, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117742, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117743, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117744, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117745, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117746, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117747, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117748, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117749, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117750, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117751, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117752, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117753, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117754, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (117755, 5) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 5;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117549, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117550, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117551, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117552, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117553, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117554, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117555, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117556, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117557, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117558, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117559, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117560, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117561, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117562, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117563, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117564, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117565, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117566, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117567, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117568, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117569, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117570, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117571, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117572, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117573, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117574, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117575, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117576, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117577, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117578, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117579, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117580, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117581, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117582, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117583, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117584, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117585, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117586, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117587, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117588, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117589, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117590, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117591, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117592, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117593, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117594, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117595, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117596, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117597, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117598, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117599, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117600, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117601, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117602, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117603, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117604, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117605, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117606, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117607, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117608, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117609, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117610, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117611, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117612, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117613, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117614, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117615, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117616, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117617, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117618, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117619, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117620, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117621, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117622, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117623, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117624, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117625, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117626, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117627, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117628, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117629, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117630, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117631, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117632, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117633, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117634, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117635, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117636, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117637, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117638, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117639, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117640, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117641, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117642, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117643, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117644, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117645, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117646, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117647, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117648, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117649, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117650, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117651, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117652, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117653, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117654, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117655, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117656, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117657, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117658, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117659, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117660, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117661, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117662, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117663, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117664, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117665, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117666, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117667, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117668, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117669, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117670, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117671, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117672, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117673, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117674, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117675, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117676, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117677, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117678, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117679, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117680, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117681, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117682, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117683, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117684, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117685, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117686, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117687, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117688, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117689, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117690, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117691, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117692, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117693, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117694, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117695, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117696, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117697, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117698, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117699, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117700, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117701, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117702, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117703, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117704, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117705, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117706, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117707, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117708, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117709, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117710, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117711, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117712, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117713, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117714, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117715, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117716, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117717, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117718, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117719, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117720, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117721, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117722, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117723, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117724, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117725, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117726, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117727, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117728, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117729, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117730, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117731, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117732, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117733, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117734, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117735, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117736, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117737, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117738, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117739, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117740, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117741, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117742, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117743, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117744, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117745, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117746, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117747, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117748, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117749, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117750, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117751, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117752, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117753, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117754, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (117755, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
