UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 102280;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 102317;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 111800;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 112721;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 112722;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 112723;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 2418;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 2419;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 2421;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 33416;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 33417;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 33418;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 33419;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 36135;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 3829;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 39472;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 39475;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 39476;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 39477;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 5120;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 51978;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52029;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52030;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52035;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52591;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52592;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52794;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52965;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 52973;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 53176;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 59773;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71390;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71395;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71396;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71397;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71398;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71399;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71400;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71401;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71402;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71403;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71404;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71405;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71408;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71432;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 71449;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88749;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88750;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88770;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88774;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88775;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88876;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88877;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88878;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88885;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88895;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88896;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88897;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88996;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 88997;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89020;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89274;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89276;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89719;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89726;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89926;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89931;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89932;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89933;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89934;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89935;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89936;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89937;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89938;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89939;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89940;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89941;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89942;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89943;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89944;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89957;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89958;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 97634;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 97946;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 97955;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 97956;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 97984;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 98295;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 98296;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 98435;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99397;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99398;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99402;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99403;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99404;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99405;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99434;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99476;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 99477;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 8130;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 8134;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89959;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89960;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89961;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89962;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89963;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89964;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89966;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89967;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89968;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89969;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89970;
UPDATE peralatan_mesin SET id_sub_skpd = 620 WHERE id = 89971;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102280;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 102317;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 111800;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112721;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112722;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112723;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2418;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2419;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 2421;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33416;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33417;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33418;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33419;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 36135;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3829;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39472;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39475;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39476;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39477;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5120;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 51978;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52029;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52030;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52035;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52591;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52592;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52794;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52965;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52973;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 53176;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59773;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71390;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71395;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71396;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71397;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71398;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71399;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71400;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71401;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71402;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71403;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71404;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71405;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71408;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71432;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71449;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88749;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88750;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88770;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88774;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88775;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88876;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88877;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88878;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88885;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88895;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88896;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88897;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88996;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88997;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89020;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89274;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89276;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89719;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89726;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89926;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89931;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89932;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89933;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89934;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89935;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89936;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89937;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89938;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89939;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89940;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89941;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89942;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89943;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89944;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89957;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89958;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97634;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97946;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97955;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97956;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97984;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98295;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98296;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98435;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99397;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99398;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99402;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99403;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99404;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99405;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99434;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99476;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99477;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8130;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8134;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89959;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89960;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89961;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89962;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89963;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89964;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89966;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89967;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89968;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89969;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89970;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89971;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102280, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (102317, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (111800, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112721, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112722, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112723, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2418, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2419, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (2421, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33416, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33417, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33418, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33419, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (36135, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3829, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39472, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39475, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39476, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39477, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5120, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (51978, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52029, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52030, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52035, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52591, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52592, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52794, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52965, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52973, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (53176, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59773, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71390, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71395, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71396, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71397, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71398, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71399, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71400, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71401, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71402, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71403, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71404, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71405, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71408, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71432, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71449, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88749, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88750, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88770, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88774, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88775, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88876, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88877, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88878, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88885, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88895, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88896, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88897, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88996, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88997, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89020, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89274, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89276, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89719, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89726, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89926, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89931, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89932, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89933, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89934, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89935, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89936, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89937, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89938, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89939, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89940, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89941, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89942, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89943, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89944, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89957, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89958, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97634, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97946, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97955, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97956, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97984, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98295, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98296, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98435, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99397, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99398, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99402, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99403, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99404, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99405, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99434, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99476, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99477, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8130, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8134, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89959, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89960, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89961, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89962, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89963, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89964, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89966, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89967, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89968, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89969, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89970, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89971, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
