UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 112736;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 112737;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 112738;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12606;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 15718;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 304;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 314;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 31965;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 33616;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3362;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3414;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3415;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3417;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3419;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3421;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3422;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3429;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3431;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3432;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3433;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3435;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3436;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3437;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3438;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3439;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3440;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 34463;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 34804;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 34805;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3521;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3727;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3777;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 3788;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 40853;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 44388;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 44412;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 44413;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 44414;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 44415;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 44427;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 50101;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5071;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5072;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5073;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5080;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5081;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5087;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5088;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5144;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5148;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5169;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5209;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5211;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5213;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5215;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 5235;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 52816;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 52817;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 67126;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 67129;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 67130;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 68137;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69240;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69241;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69242;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69243;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69244;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69245;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69246;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69247;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69251;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69252;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 87283;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 87303;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 97467;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 97468;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 97797;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 97799;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112736;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112737;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112738;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12606;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15718;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 304;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 314;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 31965;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 33616;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3362;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3414;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3415;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3417;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3419;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3421;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3422;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3429;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3431;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3432;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3433;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3435;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3436;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3437;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3438;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3439;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3440;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34463;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34804;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34805;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3521;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3727;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3777;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 3788;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40853;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44388;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44412;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44413;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44414;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44415;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 44427;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50101;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5071;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5072;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5073;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5080;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5081;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5087;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5088;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5144;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5148;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5169;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5209;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5211;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5213;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5215;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 5235;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52816;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52817;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 67126;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 67129;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 67130;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 68137;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69240;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69241;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69242;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69243;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69244;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69245;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69246;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69247;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69251;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69252;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87283;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87303;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97467;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97468;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97797;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97799;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112736, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112737, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112738, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12606, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15718, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (304, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (314, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (31965, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (33616, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3362, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3414, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3415, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3417, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3419, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3421, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3422, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3429, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3431, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3432, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3433, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3435, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3436, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3437, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3438, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3439, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3440, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34463, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34804, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34805, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3521, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3727, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3777, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (3788, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40853, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44388, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44412, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44413, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44414, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44415, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (44427, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50101, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5071, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5072, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5073, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5080, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5081, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5087, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5088, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5144, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5148, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5169, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5209, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5211, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5213, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5215, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (5235, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52816, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52817, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (67126, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (67129, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (67130, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (68137, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69240, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69241, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69242, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69243, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69244, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69245, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69246, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69247, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69251, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69252, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87283, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87303, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97467, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97468, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97797, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97799, 46) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 46;
