cvs add 01_setwan/*.php
cvs add 02_setda/*.php
cvs add 03_dpupr/*.php
cvs add 04_dishub/*.php
cvs add 05_dinkes/*.php
cvs add 07_disdik/*.php
cvs add 08_perpustakaan/*.php
cvs add 09_sosial/*.php
cvs add 10_dpmd/*.php
cvs add 11_dpppa/*.php
cvs add 12_dukcatpil/*.php
cvs add 13_pertanian/*.php
cvs add 15_dkp/*.php
cvs add 16_dkukmp/*.php
cvs add 18_dpmptsp/*.php
cvs add 19_bkd/*.php
cvs add 20_inspektorat/*.php
cvs add 21_bappeda/*.php
cvs add 22_dlh/*.php
cvs add 23_dko/*.php
cvs add 24_kesbangpol/*.php
cvs add 25_satpolpp/*.php
cvs add 26_bkppd/*.php
cvs add 28_paringin/*.php
cvs add 31_lampihong/*.php
cvs add 32_batumandi/*.php
cvs add 33_juai/*.php
cvs add 34_awayan/*.php
cvs add 35_halong/*.php
cvs add 36_paringinselatan/*.php
cvs add 38_tebingtinggi/*.php
cvs add 39_bpbd/*.php
cvs add 40_dpkp/*.php
cvs add 41_disnakertrans/*.php
cvs add 42_dppkb/*.php
cvs add 43_kominfo/*.php
cvs add 44_kearsipan/*.php
cvs add 45_perikanan/*.php
cvs add 46_pariwisata/*.php
cvs add 47_perdagangan/*.php
cvs add 48_bppd/*.php
