UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112712;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112713;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112714;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112715;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112716;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112717;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112718;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112719;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112720;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112724;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112725;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112726;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112727;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112728;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112729;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112730;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112731;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112732;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112733;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 112734;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 13015;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 1950;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 23959;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 24492;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 51797;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52031;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52032;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52033;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52034;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52797;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52802;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52969;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52970;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 52977;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 59772;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71056;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71058;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71060;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71061;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71062;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71063;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71065;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71066;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71067;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71068;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71069;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 71382;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87600;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87601;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87602;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87603;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87604;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87605;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87607;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87608;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87609;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 87610;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88763;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88764;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88766;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88767;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88768;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88769;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88771;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88772;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88773;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88866;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88868;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88869;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88880;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88881;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88886;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88887;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88888;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88889;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88894;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88899;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88900;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88901;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88902;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88903;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88904;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88905;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88906;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88907;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88992;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88993;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88994;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88995;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88998;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 88999;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89000;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89001;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89002;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89003;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89004;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89005;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89006;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89007;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89008;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89009;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89010;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89011;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89012;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89013;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89014;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89015;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89016;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89017;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89018;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89019;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89021;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89024;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89025;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89026;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89027;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89028;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89029;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89030;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89031;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89105;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89106;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89107;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89108;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89109;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89110;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89111;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89112;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89113;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89114;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89115;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89116;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89117;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89118;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89119;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89120;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89259;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89260;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89261;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89262;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89263;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89264;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89265;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89266;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89267;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89268;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89269;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89270;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89271;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89272;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89273;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89275;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89277;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89723;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89724;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89725;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89727;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89728;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89729;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89730;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89731;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89732;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89767;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89879;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89893;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89899;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89900;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89901;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89902;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89903;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89904;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89905;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89906;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89907;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89927;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89928;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89929;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89930;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89953;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89954;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89965;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 90194;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 90200;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97635;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97939;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97940;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97941;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97942;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97943;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97944;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97945;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97947;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97948;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 97949;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 98118;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99381;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99390;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99391;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99392;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99399;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99400;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99401;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99406;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99435;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99478;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 99479;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89908;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89909;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89910;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89911;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89913;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89914;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89915;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89916;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89917;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89918;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89945;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89946;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89947;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89948;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89949;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89950;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89951;
UPDATE peralatan_mesin SET id_sub_skpd = 617 WHERE id = 89952;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112712;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112713;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112714;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112715;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112716;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112717;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112718;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112719;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112720;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112724;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112725;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112726;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112727;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112728;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112729;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112730;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112731;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112732;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112733;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 112734;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 13015;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1950;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 23959;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 24492;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 51797;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52031;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52032;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52033;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52034;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52797;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52802;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52969;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52970;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 52977;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 59772;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71056;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71058;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71060;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71061;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71062;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71063;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71065;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71066;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71067;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71068;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71069;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71382;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87600;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87601;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87602;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87603;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87604;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87605;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87607;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87608;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87609;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 87610;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88763;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88764;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88766;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88767;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88768;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88769;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88771;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88772;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88773;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88866;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88868;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88869;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88880;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88881;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88886;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88887;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88888;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88889;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88894;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88899;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88900;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88901;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88902;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88903;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88904;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88905;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88906;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88907;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88992;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88993;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88994;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88995;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88998;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 88999;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89000;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89001;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89002;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89003;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89004;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89005;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89006;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89007;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89008;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89009;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89010;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89011;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89012;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89013;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89014;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89015;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89016;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89017;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89018;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89019;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89021;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89024;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89025;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89026;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89027;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89028;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89029;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89030;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89031;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89105;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89106;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89107;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89108;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89109;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89110;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89111;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89112;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89113;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89114;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89115;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89116;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89117;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89118;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89119;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89120;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89259;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89260;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89261;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89262;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89263;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89264;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89265;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89266;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89267;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89268;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89269;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89270;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89271;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89272;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89273;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89275;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89277;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89723;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89724;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89725;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89727;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89728;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89729;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89730;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89731;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89732;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89767;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89879;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89893;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89899;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89900;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89901;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89902;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89903;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89904;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89905;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89906;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89907;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89927;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89928;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89929;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89930;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89953;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89954;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89965;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90194;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 90200;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97635;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97939;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97940;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97941;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97942;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97943;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97944;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97945;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97947;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97948;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 97949;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 98118;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99381;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99390;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99391;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99392;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99399;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99400;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99401;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99406;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99435;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99478;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 99479;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89908;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89909;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89910;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89911;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89913;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89914;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89915;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89916;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89917;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89918;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89945;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89946;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89947;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89948;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89949;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89950;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89951;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 89952;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112712, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112713, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112714, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112715, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112716, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112717, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112718, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112719, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112720, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112724, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112725, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112726, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112727, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112728, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112729, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112730, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112731, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112732, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112733, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (112734, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (13015, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1950, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (23959, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (24492, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (51797, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52031, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52032, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52033, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52034, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52797, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52802, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52969, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52970, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (52977, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (59772, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71056, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71058, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71060, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71061, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71062, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71063, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71065, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71066, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71067, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71068, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71069, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71382, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87600, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87601, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87602, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87603, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87604, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87605, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87607, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87608, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87609, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (87610, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88763, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88764, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88766, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88767, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88768, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88769, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88771, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88772, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88773, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88866, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88868, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88869, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88880, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88881, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88886, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88887, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88888, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88889, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88894, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88899, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88900, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88901, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88902, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88903, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88904, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88905, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88906, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88907, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88992, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88993, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88994, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88995, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88998, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (88999, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89000, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89001, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89002, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89003, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89004, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89005, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89006, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89007, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89008, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89009, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89010, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89011, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89012, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89013, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89014, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89015, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89016, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89017, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89018, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89019, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89021, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89024, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89025, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89026, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89027, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89028, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89029, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89030, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89031, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89105, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89106, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89107, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89108, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89109, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89110, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89111, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89112, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89113, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89114, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89115, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89116, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89117, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89118, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89119, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89120, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89259, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89260, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89261, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89262, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89263, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89264, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89265, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89266, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89267, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89268, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89269, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89270, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89271, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89272, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89273, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89275, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89277, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89723, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89724, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89725, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89727, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89728, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89729, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89730, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89731, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89732, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89767, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89879, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89893, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89899, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89900, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89901, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89902, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89903, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89904, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89905, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89906, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89907, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89927, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89928, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89929, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89930, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89953, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89954, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89965, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90194, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (90200, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97635, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97939, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97940, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97941, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97942, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97943, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97944, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97945, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97947, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97948, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (97949, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (98118, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99381, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99390, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99391, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99392, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99399, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99400, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99401, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99406, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99435, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99478, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (99479, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89908, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89909, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89910, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89911, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89913, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89914, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89915, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89916, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89917, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89918, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89945, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89946, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89947, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89948, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89949, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89950, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89951, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (89952, 40) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 40;
