UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100071;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100074;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100076;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100077;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100078;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100080;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100082;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 100085;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 1015;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 1017;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 1035;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 1038;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 1044;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 1093;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12452;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12454;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12458;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12468;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12472;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12473;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 12475;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 1567;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 15715;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 15717;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 31972;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 34823;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 39364;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 40029;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 40032;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 40033;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 40034;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 40035;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 45025;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 4584;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 50204;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69107;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69108;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69109;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69110;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69122;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 69123;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 71082;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 761;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 771;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 790;
UPDATE peralatan_mesin SET id_sub_skpd = 9 WHERE id = 8514;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100071;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100074;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100076;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100077;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100078;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100080;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100082;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 100085;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1015;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1017;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1035;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1038;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1044;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1093;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12452;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12454;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12458;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12468;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12472;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12473;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 12475;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 1567;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15715;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 15717;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 31972;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 34823;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 39364;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40029;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40032;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40033;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40034;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 40035;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 45025;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 4584;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 50204;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69107;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69108;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69109;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69110;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69122;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 69123;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 71082;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 761;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 771;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 790;
UPDATE harga_peralatan_mesin SET id_asal_usul = 7, tahun_mutasi = 2021 WHERE id_peralatan_mesin = 8514;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100071, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100074, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100076, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100077, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100078, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100080, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100082, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (100085, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1015, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1017, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1035, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1038, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1044, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1093, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12452, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12454, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12458, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12468, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12472, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12473, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (12475, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (1567, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15715, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (15717, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (31972, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (34823, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (39364, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40029, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40032, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40033, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40034, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (40035, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (45025, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (4584, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (50204, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69107, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69108, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69109, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69110, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69122, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (69123, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (71082, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (761, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (771, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (790, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
INSERT INTO skpd_asal_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (8514, 11) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 11;
