UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114870;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114871;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114872;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114873;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114874;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114875;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114876;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114877;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114878;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114879;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114880;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114881;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114882;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114883;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114884;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114885;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114886;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114887;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114888;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114889;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114890;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114891;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114892;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114893;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114894;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114895;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114896;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114897;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114898;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114899;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114900;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114901;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114902;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114903;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114904;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114905;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114906;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114907;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114908;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114909;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114910;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114911;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114912;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114913;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114914;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114915;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114916;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114917;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114918;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114919;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114920;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114921;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114922;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114923;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114924;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114925;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114926;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114927;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114928;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114929;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114930;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114931;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114932;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114933;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114934;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114935;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114936;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114937;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114938;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114939;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114940;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114941;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114942;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114943;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114944;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114945;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114946;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114947;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114948;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114949;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114950;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114951;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114952;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114953;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114954;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114955;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114956;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114957;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114958;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114959;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114960;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114961;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114962;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114963;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114964;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114965;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114966;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114967;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114968;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114969;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114970;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114971;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114972;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114973;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114974;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114975;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114976;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114977;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114978;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114979;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114980;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114981;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114982;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114983;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114984;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114985;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114986;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114987;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114988;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114989;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114990;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114991;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114992;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114993;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114994;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114995;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114996;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114997;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114998;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 114999;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115000;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115001;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115002;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115003;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115004;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115005;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115006;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115007;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115008;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115009;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115010;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115011;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115012;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115013;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115014;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115015;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115016;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115017;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115018;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115019;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115020;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115021;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115022;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115023;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115024;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115025;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115026;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115027;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115028;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115029;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115030;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115031;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115032;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115033;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115034;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115035;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115036;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115037;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115038;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115039;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115040;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115041;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115042;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115043;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115044;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115045;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115046;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115047;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115048;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115049;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115050;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115051;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115052;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115053;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115054;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115055;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115056;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115057;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115058;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115059;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115060;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115061;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115062;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115063;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115064;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115065;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115066;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115067;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115068;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115069;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115070;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115071;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115072;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115073;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115074;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115075;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115076;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115077;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115078;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115079;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115080;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115081;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115082;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115083;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115084;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115085;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115086;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115087;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115088;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115089;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115090;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115091;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115092;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115093;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115094;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115095;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 115096;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114870, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114871, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114872, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114873, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114874, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114875, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114876, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114877, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114878, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114879, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114880, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114881, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114882, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114883, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114884, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114885, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114886, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114887, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114888, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114889, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114890, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114891, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114892, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114893, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114894, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114895, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114896, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114897, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114898, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114899, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114900, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114901, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114902, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114903, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114904, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114905, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114906, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114907, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114908, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114909, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114910, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114911, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114912, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114913, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114914, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114915, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114916, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114917, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114918, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114919, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114920, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114921, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114922, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114923, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114924, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114925, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114926, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114927, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114928, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114929, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114930, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114931, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114932, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114933, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114934, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114935, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114936, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114937, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114938, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114939, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114940, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114941, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114942, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114943, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114944, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114945, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114946, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114947, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114948, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114949, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114950, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114951, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114952, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114953, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114954, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114955, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114956, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114957, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114958, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114959, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114960, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114961, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114962, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114963, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114964, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114965, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114966, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114967, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114968, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114969, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114970, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114971, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114972, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114973, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114974, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114975, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114976, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114977, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114978, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114979, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114980, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114981, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114982, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114983, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114984, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114985, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114986, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114987, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114988, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114989, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114990, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114991, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114992, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114993, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114994, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114995, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114996, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114997, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114998, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (114999, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115000, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115001, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115002, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115003, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115004, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115005, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115006, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115007, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115008, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115009, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115010, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115011, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115012, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115013, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115014, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115015, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115016, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115017, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115018, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115019, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115020, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115021, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115022, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115023, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115024, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115025, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115026, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115027, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115028, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115029, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115030, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115031, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115032, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115033, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115034, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115035, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115036, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115037, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115038, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115039, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115040, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115041, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115042, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115043, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115044, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115045, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115046, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115047, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115048, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115049, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115050, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115051, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115052, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115053, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115054, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115055, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115056, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115057, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115058, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115059, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115060, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115061, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115062, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115063, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115064, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115065, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115066, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115067, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115068, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115069, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115070, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115071, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115072, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115073, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115074, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115075, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115076, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115077, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115078, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115079, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115080, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115081, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115082, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115083, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115084, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115085, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115086, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115087, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115088, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115089, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115090, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115091, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115092, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115093, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115094, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115095, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (115096, 16) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 16;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114870, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114871, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114872, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114873, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114874, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114875, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114876, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114877, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114878, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114879, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114880, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114881, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114882, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114883, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114884, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114885, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114886, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114887, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114888, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114889, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114890, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114891, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114892, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114893, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114894, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114895, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114896, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114897, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114898, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114899, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114900, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114901, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114902, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114903, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114904, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114905, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114906, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114907, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114908, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114909, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114910, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114911, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114912, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114913, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114914, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114915, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114916, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114917, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114918, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114919, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114920, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114921, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114922, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114923, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114924, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114925, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114926, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114927, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114928, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114929, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114930, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114931, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114932, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114933, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114934, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114935, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114936, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114937, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114938, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114939, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114940, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114941, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114942, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114943, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114944, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114945, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114946, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114947, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114948, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114949, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114950, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114951, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114952, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114953, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114954, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114955, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114956, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114957, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114958, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114959, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114960, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114961, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114962, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114963, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114964, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114965, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114966, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114967, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114968, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114969, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114970, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114971, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114972, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114973, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114974, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114975, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114976, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114977, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114978, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114979, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114980, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114981, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114982, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114983, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114984, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114985, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114986, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114987, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114988, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114989, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114990, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114991, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114992, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114993, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114994, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114995, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114996, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114997, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114998, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (114999, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115000, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115001, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115002, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115003, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115004, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115005, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115006, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115007, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115008, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115009, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115010, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115011, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115012, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115013, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115014, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115015, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115016, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115017, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115018, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115019, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115020, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115021, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115022, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115023, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115024, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115025, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115026, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115027, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115028, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115029, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115030, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115031, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115032, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115033, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115034, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115035, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115036, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115037, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115038, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115039, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115040, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115041, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115042, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115043, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115044, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115045, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115046, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115047, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115048, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115049, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115050, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115051, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115052, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115053, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115054, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115055, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115056, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115057, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115058, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115059, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115060, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115061, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115062, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115063, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115064, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115065, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115066, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115067, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115068, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115069, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115070, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115071, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115072, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115073, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115074, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115075, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115076, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115077, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115078, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115079, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115080, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115081, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115082, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115083, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115084, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115085, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115086, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115087, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115088, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115089, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115090, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115091, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115092, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115093, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115094, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115095, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (115096, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
