cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/setda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>2/g >  02_setda/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dpupr/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>3/g >  03_dpupr/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dishub/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>4/g >  04_dishub/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dinkes/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>5/g >  05_dinkes/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/rsud/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>6/g >  06_rsud/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/disdik/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>7/g >  07_disdik/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/perpustakaan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>8/g >  08_perpustakaan/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/sosial/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>9/g >  09_sosial/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dpmd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>10/g >  10_dpmd/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dpppa/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>11/g >  11_dpppa/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dukcatpil/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>12/g >  12_dukcatpil/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/pertanian/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>13/g >  13_pertanian/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/kehutanan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>14/g >  14_kehutanan/peralatanmesinskpd.xml
#cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dkp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\15/g >  15_dkp/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dkukmp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>16/g >  16_dkukmp/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/distamben/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>17/g >  17_distamben/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dpmptsp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>18/g >  18_dpmptsp/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/bkd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>19/g >  19_bkd/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/inspektorat/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>20/g >  20_inspektorat/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/bappeda/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>21/g >  21_bappeda/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dlh/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>22/g >  22_dlh/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dko/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>23/g >  23_dko/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/kesbangpol/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>24/g >  24_kesbangpol/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/satpolpp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>25/g >  25_satpolpp/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/bkppd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>26/g >  26_bkppd/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/korpri/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>27/g >  27_korpri/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/paringin/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>28/g >  28_paringin/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/paringinkota/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>29/g >  29_paringinkota/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/paringintimur/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>30/g >  30_paringintimur/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/lampihong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>31/g >  31_lampihong/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/batumandi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>32/g >  32_batumandi/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/juai/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>33/g >  33_juai/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/awayan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>34/g >  34_awayan/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/halong/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>35/g >  35_halong/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/paringinselatan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>36/g >  36_paringinselatan/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/batupiring/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>37/g >  37_batupiring/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/tebingtinggi/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>38/g >  38_tebingtinggi/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/bpbd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>39/g >  39_bpbd/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dpkp/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>40/g >  40_dpkp/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/disnakertrans/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>41/g >  41_disnakertrans/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/dppkb/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>42/g >  42_dppkb/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/kominfo/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>43/g >  43_kominfo/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/kearsipan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>44/g >  44_kearsipan/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/perikanan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>45/g >  45_perikanan/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/pariwisata/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>46/g >  46_pariwisata/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/perdagangan/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>47/g >  47_perdagangan/peralatanmesinskpd.xml
cat 01_setwan/peralatanmesinskpd.xml | sed -e s/setwan/bppd/g  | sed -e s/\<CriteriaDefaults\>1/\<CriteriaDefaults\>48/g >  48_bppd/peralatanmesinskpd.xml
