cat peralatan_mesin_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"skpd.id = 1"/"skpd.id = 2"/g > peralatan_mesin_setda.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"skpd.id = 1"/"skpd.id = 3"/g > peralatan_mesin_dispu.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"skpd.id = 1"/"skpd.id = 4"/g > peralatan_mesin_dishub.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"skpd.id = 1"/"skpd.id = 5"/g > peralatan_mesin_dinkes.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"skpd.id = 1"/"skpd.id = 6"/g > peralatan_mesin_rsud.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"skpd.id = 1"/"skpd.id = 7"/g > peralatan_mesin_disdik.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"skpd.id = 1"/"skpd.id = 8"/g > peralatan_mesin_kpdad.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"skpd.id = 1"/"skpd.id = 9"/g > peralatan_mesin_snt.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"skpd.id = 1"/"skpd.id = 10"/g > peralatan_mesin_bpmpd.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"skpd.id = 1"/"skpd.id = 11"/g > peralatan_mesin_bppakb.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"skpd.id = 1"/"skpd.id = 12"/g > peralatan_mesin_dukcatpil.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"skpd.id = 1"/"skpd.id = 13"/g > peralatan_mesin_pertanian.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"skpd.id = 1"/"skpd.id = 14"/g > peralatan_mesin_kehutanan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"skpd.id = 1"/"skpd.id = 15"/g > peralatan_mesin_bppkp.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"skpd.id = 1"/"skpd.id = 16"/g > peralatan_mesin_perindagkop.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"skpd.id = 1"/"skpd.id = 17"/g > peralatan_mesin_distamben.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"skpd.id = 1"/"skpd.id = 18"/g > peralatan_mesin_kp2tpm.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"skpd.id = 1"/"skpd.id = 19"/g > peralatan_mesin_dppkad.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"skpd.id = 1"/"skpd.id = 20"/g > peralatan_mesin_inspektorat.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"skpd.id = 1"/"skpd.id = 21"/g > peralatan_mesin_bappeda.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"skpd.id = 1"/"skpd.id = 22"/g > peralatan_mesin_blhk.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"skpd.id = 1"/"skpd.id = 23"/g > peralatan_mesin_disporaparbud.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"skpd.id = 1"/"skpd.id = 24"/g > peralatan_mesin_kesbangpol.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"skpd.id = 1"/"skpd.id = 25"/g > peralatan_mesin_satpolpp.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"skpd.id = 1"/"skpd.id = 26"/g > peralatan_mesin_bkd.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"skpd.id = 1"/"skpd.id = 27"/g > peralatan_mesin_korpri.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"skpd.id = 1"/"skpd.id = 28"/g > peralatan_mesin_paringin.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"skpd.id = 1"/"skpd.id = 29"/g > peralatan_mesin_paringinkota.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"skpd.id = 1"/"skpd.id = 30"/g > peralatan_mesin_paringintimur.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"skpd.id = 1"/"skpd.id = 31"/g > peralatan_mesin_lampihong.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"skpd.id = 1"/"skpd.id = 32"/g > peralatan_mesin_batumandi.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"skpd.id = 1"/"skpd.id = 33"/g > peralatan_mesin_juai.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"skpd.id = 1"/"skpd.id = 34"/g > peralatan_mesin_awayan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"skpd.id = 1"/"skpd.id = 35"/g > peralatan_mesin_halong.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"skpd.id = 1"/"skpd.id = 36"/g > peralatan_mesin_paringinselatan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"skpd.id = 1"/"skpd.id = 37"/g > peralatan_mesin_batupiring.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"skpd.id = 1"/"skpd.id = 38"/g > peralatan_mesin_tebingtinggi.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"skpd.id = 1"/"skpd.id = 39"/g > peralatan_mesin_bpbd.sql

cat peralatan_mesin_setwan.sql | sed -e s/setwan/b40/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > peralatan_mesin_b40.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b41/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > peralatan_mesin_b41.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b42/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > peralatan_mesin_b42.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b43/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > peralatan_mesin_b43.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b44/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > peralatan_mesin_b44.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b45/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > peralatan_mesin_b45.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b46/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > peralatan_mesin_b46.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b47/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > peralatan_mesin_b47.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/b48/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > peralatan_mesin_b48.sql

cat peralatan_mesin_*.sql > ../gabungan_peralatan_mesin.sql
