cat peralatan_mesin_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"skpd.id = 1"/"skpd.id = 2"/g > peralatan_mesin_setda.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dpupr/g | sed -e s/"skpd.id = 1"/"skpd.id = 3"/g > peralatan_mesin_dpupr.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"skpd.id = 1"/"skpd.id = 4"/g > peralatan_mesin_dishub.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"skpd.id = 1"/"skpd.id = 5"/g > peralatan_mesin_dinkes.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"skpd.id = 1"/"skpd.id = 6"/g > peralatan_mesin_rsud.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"skpd.id = 1"/"skpd.id = 7"/g > peralatan_mesin_disdik.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/perpustakaan/g | sed -e s/"skpd.id = 1"/"skpd.id = 8"/g > peralatan_mesin_perpustakaan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/sosial/g | sed -e s/"skpd.id = 1"/"skpd.id = 9"/g > peralatan_mesin_sosial.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dpmd/g | sed -e s/"skpd.id = 1"/"skpd.id = 10"/g > peralatan_mesin_dpmd.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dpppa/g | sed -e s/"skpd.id = 1"/"skpd.id = 11"/g > peralatan_mesin_dpppa.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"skpd.id = 1"/"skpd.id = 12"/g > peralatan_mesin_dukcatpil.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"skpd.id = 1"/"skpd.id = 13"/g > peralatan_mesin_pertanian.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"skpd.id = 1"/"skpd.id = 14"/g > peralatan_mesin_kehutanan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dkp/g | sed -e s/"skpd.id = 1"/"skpd.id = 15"/g > peralatan_mesin_dkp.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dkukmp/g | sed -e s/"skpd.id = 1"/"skpd.id = 16"/g > peralatan_mesin_dkukmp.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"skpd.id = 1"/"skpd.id = 17"/g > peralatan_mesin_distamben.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dpmptsp/g | sed -e s/"skpd.id = 1"/"skpd.id = 18"/g > peralatan_mesin_dpmptsp.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"skpd.id = 1"/"skpd.id = 19"/g > peralatan_mesin_bkd.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"skpd.id = 1"/"skpd.id = 20"/g > peralatan_mesin_inspektorat.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"skpd.id = 1"/"skpd.id = 21"/g > peralatan_mesin_bappeda.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dlh/g | sed -e s/"skpd.id = 1"/"skpd.id = 22"/g > peralatan_mesin_dlh.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dko/g | sed -e s/"skpd.id = 1"/"skpd.id = 23"/g > peralatan_mesin_dko.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"skpd.id = 1"/"skpd.id = 24"/g > peralatan_mesin_kesbangpol.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"skpd.id = 1"/"skpd.id = 25"/g > peralatan_mesin_satpolpp.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bkppd/g | sed -e s/"skpd.id = 1"/"skpd.id = 26"/g > peralatan_mesin_bkppd.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"skpd.id = 1"/"skpd.id = 27"/g > peralatan_mesin_korpri.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"skpd.id = 1"/"skpd.id = 28"/g > peralatan_mesin_paringin.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"skpd.id = 1"/"skpd.id = 29"/g > peralatan_mesin_paringinkota.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"skpd.id = 1"/"skpd.id = 30"/g > peralatan_mesin_paringintimur.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"skpd.id = 1"/"skpd.id = 31"/g > peralatan_mesin_lampihong.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"skpd.id = 1"/"skpd.id = 32"/g > peralatan_mesin_batumandi.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"skpd.id = 1"/"skpd.id = 33"/g > peralatan_mesin_juai.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"skpd.id = 1"/"skpd.id = 34"/g > peralatan_mesin_awayan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"skpd.id = 1"/"skpd.id = 35"/g > peralatan_mesin_halong.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"skpd.id = 1"/"skpd.id = 36"/g > peralatan_mesin_paringinselatan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"skpd.id = 1"/"skpd.id = 37"/g > peralatan_mesin_batupiring.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"skpd.id = 1"/"skpd.id = 38"/g > peralatan_mesin_tebingtinggi.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"skpd.id = 1"/"skpd.id = 39"/g > peralatan_mesin_bpbd.sql

cat peralatan_mesin_setwan.sql | sed -e s/setwan/dpkp/g | sed -e s/"skpd.id = 1"/"skpd.id = 40"/g > peralatan_mesin_dpkp.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/disnakertrans/g | sed -e s/"skpd.id = 1"/"skpd.id = 41"/g > peralatan_mesin_disnakertrans.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/dppkb/g | sed -e s/"skpd.id = 1"/"skpd.id = 42"/g > peralatan_mesin_dppkb.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kominfo/g | sed -e s/"skpd.id = 1"/"skpd.id = 43"/g > peralatan_mesin_kominfo.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/kearsipan/g | sed -e s/"skpd.id = 1"/"skpd.id = 44"/g > peralatan_mesin_kearsipan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/perikanan/g | sed -e s/"skpd.id = 1"/"skpd.id = 45"/g > peralatan_mesin_perikanan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/pariwisata/g | sed -e s/"skpd.id = 1"/"skpd.id = 46"/g > peralatan_mesin_pariwisata.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/perdagangan/g | sed -e s/"skpd.id = 1"/"skpd.id = 47"/g > peralatan_mesin_perdagangan.sql
cat peralatan_mesin_setwan.sql | sed -e s/setwan/bppd/g | sed -e s/"skpd.id = 1"/"skpd.id = 48"/g > peralatan_mesin_bppd.sql

cat peralatan_mesin_*.sql > ../gabungan_peralatan_mesin.sql
