cat tanah_setwan.sql | sed -e s/setwan/setda/g | sed -e s/"id_skpd = 1"/"id_skpd = 2"/g > tanah_setda.sql
cat tanah_setwan.sql | sed -e s/setwan/dispu/g | sed -e s/"id_skpd = 1"/"id_skpd = 3"/g > tanah_dispu.sql
cat tanah_setwan.sql | sed -e s/setwan/dishub/g | sed -e s/"id_skpd = 1"/"id_skpd = 4"/g > tanah_dishub.sql
cat tanah_setwan.sql | sed -e s/setwan/dinkes/g | sed -e s/"id_skpd = 1"/"id_skpd = 5"/g > tanah_dinkes.sql
cat tanah_setwan.sql | sed -e s/setwan/rsud/g | sed -e s/"id_skpd = 1"/"id_skpd = 6"/g > tanah_rsud.sql
cat tanah_setwan.sql | sed -e s/setwan/disdik/g | sed -e s/"id_skpd = 1"/"id_skpd = 7"/g > tanah_disdik.sql
cat tanah_setwan.sql | sed -e s/setwan/kpdad/g | sed -e s/"id_skpd = 1"/"id_skpd = 8"/g > tanah_kpdad.sql
cat tanah_setwan.sql | sed -e s/setwan/snt/g | sed -e s/"id_skpd = 1"/"id_skpd = 9"/g > tanah_snt.sql
cat tanah_setwan.sql | sed -e s/setwan/bpmpd/g | sed -e s/"id_skpd = 1"/"id_skpd = 10"/g > tanah_bpmpd.sql
cat tanah_setwan.sql | sed -e s/setwan/bppakb/g | sed -e s/"id_skpd = 1"/"id_skpd = 11"/g > tanah_bppakb.sql
cat tanah_setwan.sql | sed -e s/setwan/dukcatpil/g | sed -e s/"id_skpd = 1"/"id_skpd = 12"/g > tanah_dukcatpil.sql
cat tanah_setwan.sql | sed -e s/setwan/pertanian/g | sed -e s/"id_skpd = 1"/"id_skpd = 13"/g > tanah_pertanian.sql
cat tanah_setwan.sql | sed -e s/setwan/kehutanan/g | sed -e s/"id_skpd = 1"/"id_skpd = 14"/g > tanah_kehutanan.sql
cat tanah_setwan.sql | sed -e s/setwan/bppkp/g | sed -e s/"id_skpd = 1"/"id_skpd = 15"/g > tanah_bppkp.sql
cat tanah_setwan.sql | sed -e s/setwan/perindagkop/g | sed -e s/"id_skpd = 1"/"id_skpd = 16"/g > tanah_perindagkop.sql
cat tanah_setwan.sql | sed -e s/setwan/distamben/g | sed -e s/"id_skpd = 1"/"id_skpd = 17"/g > tanah_distamben.sql
cat tanah_setwan.sql | sed -e s/setwan/kp2tpm/g | sed -e s/"id_skpd = 1"/"id_skpd = 18"/g > tanah_kp2tpm.sql
cat tanah_setwan.sql | sed -e s/setwan/dppkad/g | sed -e s/"id_skpd = 1"/"id_skpd = 19"/g > tanah_dppkad.sql
cat tanah_setwan.sql | sed -e s/setwan/inspektorat/g | sed -e s/"id_skpd = 1"/"id_skpd = 20"/g > tanah_inspektorat.sql
cat tanah_setwan.sql | sed -e s/setwan/bappeda/g | sed -e s/"id_skpd = 1"/"id_skpd = 21"/g > tanah_bappeda.sql
cat tanah_setwan.sql | sed -e s/setwan/blhk/g | sed -e s/"id_skpd = 1"/"id_skpd = 22"/g > tanah_blhk.sql
cat tanah_setwan.sql | sed -e s/setwan/disporaparbud/g | sed -e s/"id_skpd = 1"/"id_skpd = 23"/g > tanah_disporaparbud.sql
cat tanah_setwan.sql | sed -e s/setwan/kesbangpol/g | sed -e s/"id_skpd = 1"/"id_skpd = 24"/g > tanah_kesbangpol.sql
cat tanah_setwan.sql | sed -e s/setwan/satpolpp/g | sed -e s/"id_skpd = 1"/"id_skpd = 25"/g > tanah_satpolpp.sql
cat tanah_setwan.sql | sed -e s/setwan/bkd/g | sed -e s/"id_skpd = 1"/"id_skpd = 26"/g > tanah_bkd.sql
cat tanah_setwan.sql | sed -e s/setwan/korpri/g | sed -e s/"id_skpd = 1"/"id_skpd = 27"/g > tanah_korpri.sql
cat tanah_setwan.sql | sed -e s/setwan/paringin/g | sed -e s/"id_skpd = 1"/"id_skpd = 28"/g > tanah_paringin.sql
cat tanah_setwan.sql | sed -e s/setwan/paringinkota/g | sed -e s/"id_skpd = 1"/"id_skpd = 29"/g > tanah_paringinkota.sql
cat tanah_setwan.sql | sed -e s/setwan/paringintimur/g | sed -e s/"id_skpd = 1"/"id_skpd = 30"/g > tanah_paringintimur.sql
cat tanah_setwan.sql | sed -e s/setwan/lampihong/g | sed -e s/"id_skpd = 1"/"id_skpd = 31"/g > tanah_lampihong.sql
cat tanah_setwan.sql | sed -e s/setwan/batumandi/g | sed -e s/"id_skpd = 1"/"id_skpd = 32"/g > tanah_batumandi.sql
cat tanah_setwan.sql | sed -e s/setwan/juai/g | sed -e s/"id_skpd = 1"/"id_skpd = 33"/g > tanah_juai.sql
cat tanah_setwan.sql | sed -e s/setwan/awayan/g | sed -e s/"id_skpd = 1"/"id_skpd = 34"/g > tanah_awayan.sql
cat tanah_setwan.sql | sed -e s/setwan/halong/g | sed -e s/"id_skpd = 1"/"id_skpd = 35"/g > tanah_halong.sql
cat tanah_setwan.sql | sed -e s/setwan/paringinselatan/g | sed -e s/"id_skpd = 1"/"id_skpd = 36"/g > tanah_paringinselatan.sql
cat tanah_setwan.sql | sed -e s/setwan/batupiring/g | sed -e s/"id_skpd = 1"/"id_skpd = 37"/g > tanah_batupiring.sql
cat tanah_setwan.sql | sed -e s/setwan/tebingtinggi/g | sed -e s/"id_skpd = 1"/"id_skpd = 38"/g > tanah_tebingtinggi.sql
cat tanah_setwan.sql | sed -e s/setwan/bpbd/g | sed -e s/"id_skpd = 1"/"id_skpd = 39"/g > tanah_bpbd.sql

cat tanah_setwan.sql | sed -e s/setwan/b40/g | sed -e s/"id_skpd = 1"/"id_skpd = 40"/g > tanah_b40.sql
cat tanah_setwan.sql | sed -e s/setwan/b41/g | sed -e s/"id_skpd = 1"/"id_skpd = 41"/g > tanah_b41.sql
cat tanah_setwan.sql | sed -e s/setwan/b42/g | sed -e s/"id_skpd = 1"/"id_skpd = 42"/g > tanah_b42.sql
cat tanah_setwan.sql | sed -e s/setwan/b43/g | sed -e s/"id_skpd = 1"/"id_skpd = 43"/g > tanah_b43.sql
cat tanah_setwan.sql | sed -e s/setwan/b44/g | sed -e s/"id_skpd = 1"/"id_skpd = 44"/g > tanah_b44.sql
cat tanah_setwan.sql | sed -e s/setwan/b45/g | sed -e s/"id_skpd = 1"/"id_skpd = 45"/g > tanah_b45.sql
cat tanah_setwan.sql | sed -e s/setwan/b46/g | sed -e s/"id_skpd = 1"/"id_skpd = 46"/g > tanah_b46.sql
cat tanah_setwan.sql | sed -e s/setwan/b47/g | sed -e s/"id_skpd = 1"/"id_skpd = 47"/g > tanah_b47.sql
cat tanah_setwan.sql | sed -e s/setwan/b48/g | sed -e s/"id_skpd = 1"/"id_skpd = 48"/g > tanah_b48.sql

cat tanah_*.sql > ../gabungan_tanah.sql
