UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118375;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118376;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118377;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118378;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118379;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118380;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118381;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118382;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118383;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118384;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118385;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118386;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118387;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118388;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118389;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118390;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118391;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118392;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118393;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118394;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118395;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118396;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118397;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118398;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118399;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118400;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118401;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118402;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118403;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118404;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118405;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118406;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118407;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118408;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118409;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118410;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118411;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118412;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118413;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118414;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118415;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118416;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118417;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118418;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118419;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118420;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118421;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118422;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118423;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118424;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118425;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118426;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118427;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118428;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118429;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118430;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118431;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118432;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118433;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118434;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118435;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118436;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118437;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118438;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118439;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118440;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118441;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118442;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118443;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118444;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118445;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118446;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118447;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118448;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118449;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118450;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118451;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118452;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118453;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118454;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118455;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118456;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118457;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118458;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118459;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118460;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118461;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118462;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118463;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118464;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118465;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118466;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118467;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118468;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118469;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118470;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118471;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118472;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118473;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118474;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118475;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118476;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118477;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118478;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118479;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118480;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118481;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118482;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118483;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118484;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118485;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118486;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118487;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118488;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118489;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118490;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118491;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118492;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118493;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118494;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118495;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118496;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118497;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118498;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118499;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118500;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118501;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118502;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118503;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118504;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118505;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118506;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118507;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118508;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118509;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118510;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118511;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118512;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118513;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118514;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118515;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118516;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118517;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118518;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118519;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118520;
UPDATE peralatan_mesin SET id_mutasi_berkurang = 2 WHERE id = 118521;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118375, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118376, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118377, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118378, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118379, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118380, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118381, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118382, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118383, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118384, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118385, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118386, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118387, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118388, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118389, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118390, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118391, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118392, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118393, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118394, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118395, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118396, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118397, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118398, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118399, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118400, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118401, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118402, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118403, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118404, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118405, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118406, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118407, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118408, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118409, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118410, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118411, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118412, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118413, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118414, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118415, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118416, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118417, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118418, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118419, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118420, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118421, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118422, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118423, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118424, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118425, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118426, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118427, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118428, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118429, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118430, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118431, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118432, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118433, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118434, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118435, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118436, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118437, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118438, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118439, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118440, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118441, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118442, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118443, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118444, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118445, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118446, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118447, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118448, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118449, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118450, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118451, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118452, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118453, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118454, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118455, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118456, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118457, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118458, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118459, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118460, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118461, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118462, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118463, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118464, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118465, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118466, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118467, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118468, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118469, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118470, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118471, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118472, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118473, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118474, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118475, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118476, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118477, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118478, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118479, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118480, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118481, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118482, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118483, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118484, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118485, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118486, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118487, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118488, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118489, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118490, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118491, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118492, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118493, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118494, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118495, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118496, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118497, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118498, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118499, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118500, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118501, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118502, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118503, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118504, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118505, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118506, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118507, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118508, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118509, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118510, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118511, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118512, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118513, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118514, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118515, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118516, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118517, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118518, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118519, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118520, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO skpd_tujuan_peralatan_mesin (id_peralatan_mesin, id_skpd) VALUES (118521, 21) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET id_skpd = 21;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118375, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118376, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118377, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118378, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118379, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118380, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118381, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118382, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118383, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118384, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118385, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118386, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118387, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118388, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118389, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118390, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118391, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118392, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118393, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118394, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118395, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118396, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118397, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118398, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118399, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118400, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118401, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118402, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118403, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118404, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118405, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118406, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118407, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118408, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118409, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118410, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118411, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118412, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118413, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118414, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118415, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118416, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118417, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118418, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118419, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118420, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118421, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118422, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118423, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118424, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118425, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118426, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118427, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118428, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118429, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118430, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118431, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118432, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118433, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118434, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118435, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118436, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118437, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118438, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118439, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118440, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118441, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118442, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118443, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118444, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118445, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118446, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118447, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118448, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118449, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118450, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118451, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118452, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118453, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118454, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118455, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118456, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118457, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118458, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118459, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118460, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118461, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118462, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118463, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118464, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118465, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118466, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118467, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118468, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118469, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118470, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118471, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118472, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118473, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118474, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118475, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118476, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118477, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118478, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118479, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118480, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118481, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118482, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118483, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118484, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118485, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118486, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118487, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118488, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118489, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118490, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118491, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118492, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118493, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118494, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118495, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118496, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118497, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118498, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118499, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118500, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118501, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118502, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118503, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118504, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118505, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118506, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118507, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118508, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118509, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118510, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118511, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118512, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118513, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118514, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118515, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118516, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118517, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118518, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118519, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118520, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_peralatan_mesin (id_peralatan_mesin, tahun_berkurang) VALUES (118521, 2021) ON CONFLICT (id_peralatan_mesin) DO UPDATE SET tahun_berkurang = 2021;
