UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6648;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6649;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6650;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6651;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6652;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6653;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6654;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6655;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6656;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6657;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6658;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6659;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6660;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6661;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6662;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6663;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6664;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6665;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6666;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6667;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6668;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6669;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6670;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6671;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6672;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6673;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6674;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6675;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6676;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6677;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6678;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6679;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6680;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6681;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6682;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6683;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6684;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6685;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6686;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6687;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6688;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6689;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6690;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6691;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6692;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6693;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6694;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6695;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6696;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6697;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6698;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6699;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6700;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6701;
UPDATE gedung_bangunan SET id_mutasi_berkurang = 2 WHERE id = 6702;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6648, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6649, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6650, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6651, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6652, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6653, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6654, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6655, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6656, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6657, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6658, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6659, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6660, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6661, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6662, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6663, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6664, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6665, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6666, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6667, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6668, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6669, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6670, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6671, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6672, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6673, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6674, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6675, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6676, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6677, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6678, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6679, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6680, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6681, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6682, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6683, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6684, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6685, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6686, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6687, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6688, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6689, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6690, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6691, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6692, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6693, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6694, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6695, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6696, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6697, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6698, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6699, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6700, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6701, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_gedung_bangunan (id_gedung_bangunan, id_skpd) VALUES (6702, 13) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET id_skpd = 13;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6648, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6649, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6650, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6651, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6652, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6653, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6654, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6655, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6656, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6657, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6658, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6659, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6660, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6661, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6662, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6663, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6664, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6665, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6666, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6667, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6668, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6669, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6670, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6671, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6672, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6673, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6674, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6675, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6676, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6677, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6678, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6679, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6680, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6681, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6682, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6683, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6684, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6685, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6686, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6687, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6688, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6689, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6690, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6691, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6692, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6693, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6694, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6695, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6696, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6697, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6698, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6699, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6700, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6701, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_gedung_bangunan (id_gedung_bangunan, tahun_berkurang) VALUES (6702, 2021) ON CONFLICT (id_gedung_bangunan) DO UPDATE SET tahun_berkurang = 2021;
