UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5424;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5425;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5426;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5427;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5428;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5429;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5430;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5431;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5432;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5433;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5434;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5435;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5436;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5437;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5438;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5439;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5440;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5441;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5442;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5443;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5444;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5445;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5446;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5447;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5448;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5449;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5450;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5451;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5452;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5453;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5454;
UPDATE jalan_irigasi_jaringan SET id_mutasi_berkurang = 2 WHERE id = 5455;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5424, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5425, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5426, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5427, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5428, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5429, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5430, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5431, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5432, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5433, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5434, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5435, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5436, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5437, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5438, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5439, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5440, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5441, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5442, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5443, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5444, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5445, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5446, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5447, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5448, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5449, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5450, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5451, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5452, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5453, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5454, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO skpd_tujuan_jalan_irigasi_jaringan (id_jalan_irigasi_jaringan, id_skpd) VALUES (5455, 13) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET id_skpd = 13;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5424, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5425, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5426, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5427, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5428, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5429, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5430, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5431, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5432, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5433, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5434, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5435, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5436, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5437, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5438, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5439, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5440, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5441, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5442, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5443, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5444, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5445, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5446, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5447, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5448, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5449, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5450, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5451, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5452, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5453, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5454, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
INSERT INTO tahun_berkurang_jij (id_jalan_irigasi_jaringan, tahun_berkurang) VALUES (5455, 2021) ON CONFLICT (id_jalan_irigasi_jaringan) DO UPDATE SET tahun_berkurang = 2021;
